//! The native backend: core IR to Rust source.
//!
//! Per specification 18.3, the first native backend lowers typed Korben IR to
//! generated Rust and hands it to an isolated Rust compilation pipeline. The
//! generated source is internal but reproducible, and `korben build --emit rust`
//! prints it.
//!
//! Generated code links against `korben-runtime`, the same crate the
//! interpreter uses, so both execution modes share their standard library and
//! their notion of what a value is.

// korben-vtx

use crate::ir::{self, Expr, Pattern, Program, Ref, Stmt};
use korben_runtime::Loc;
use korben_syntax::diag::Diagnostic;
use korben_syntax::SourceMap;
use std::collections::HashMap;
use std::fmt::Write as _;

/// What a mangled global symbol refers to.
#[derive(Clone, Copy, PartialEq)]
enum Symbol {
    Function,
    /// An async function: calling it yields a task, so it must go through
    /// `apply` rather than being called directly.
    AsyncFunction,
    Const,
}

pub struct Generated {
    pub main: String,
    /// File name and text of every source file, indexed by file id.
    pub sources: Vec<(String, String)>,
}

/// Emit the Rust source for a program.
pub fn generate(program: &Program, sources: &SourceMap) -> Result<Generated, Vec<Diagnostic>> {
    // Every builtin the program references must exist in the runtime.
    let mut missing = Vec::new();
    for name in &program.builtins {
        if korben_runtime::std::builtin(name).is_none() {
            missing.push(name.clone());
        }
    }
    if !missing.is_empty() {
        return Err(missing
            .into_iter()
            .map(|name| {
                Diagnostic::error(format!("`{name}` has no native implementation"))
                    .with_code("missing-runtime")
                    .note("the interpreter provides it, but the native backend does not yet")
                    .help("run this program with `korben run` until the backend catches up")
            })
            .collect());
    }

    let mut symbols = HashMap::new();
    for module in &program.modules {
        for function in &module.functions {
            let kind = if function.is_async { Symbol::AsyncFunction } else { Symbol::Function };
            symbols.insert(function.symbol.clone(), kind);
        }
        for foreign in &module.foreign {
            symbols.insert(foreign.symbol.clone(), Symbol::Function);
        }
        for konst in &module.consts {
            symbols.insert(konst.symbol.clone(), Symbol::Const);
        }
    }

    let mut generator = Generator {
        out: String::new(),
        symbols,
        next_label: 0,
        next_temp: 0,
        next_lambda: 0,
        pending: String::new(),
        error_labels: Vec::new(),
        leaves: false,
        recur_labels: Vec::new(),
        // korben-d3j
        builtin_slots: program
            .builtins
            .iter()
            .enumerate()
            .map(|(slot, name)| (name.clone(), slot))
            .collect(),
        // korben-b13
        types: program.types.clone(),
    };
    generator.program(program);

    let mut files = Vec::new();
    let mut index = 0u32;
    while let Some(file) = sources.get(index) {
        files.push((file.name.clone(), file.text.clone()));
        index += 1;
    }
    Ok(Generated { main: generator.out, sources: files })
}

struct Generator {
    out: String,
    symbols: HashMap<String, Symbol>,
    next_label: usize,
    next_temp: usize,
    next_lambda: usize,
    /// Top-level items produced while compiling an expression.
    pending: String,
    /// Innermost-last stack of labels that capture an error.
    error_labels: Vec<String>,
    // korben-str
    /// Set when the expression just generated always leaves -- every path
    /// through it breaks. Wrapping such an expression in `Ok(..)` produces
    /// code rustc can see is unreachable, and says so.
    leaves: bool,
    /// Innermost-last stack of labels a `recur` targets.
    recur_labels: Vec<String>,
    // korben-d3j
    /// The slot each referenced builtin was given, by name.
    builtin_slots: HashMap<String, usize>,
    // korben-b13
    /// What the checker concluded, so a call can be specialised when the
    /// answer is not in doubt.
    types: HashMap<korben_syntax::Span, crate::types::Type>,
}

const PRELUDE: &str = r#"// Generated by the Korben compiler. Do not edit.
// The crate carries every function the program's modules define, including
// ones it never calls. Emitting only what is reachable was measured and turned
// down: the linker drops them from the binary anyway, and doing it here saved
// about one per cent of a build in exchange for an analysis that silently
// miscompiles if it gets its roots wrong. This is the only lint this file
// switches off.
#![allow(dead_code)]
// korben-str
// A generator emits labels it may not use and arms after one that always
// matches. Those are shapes, not mistakes, and the person who ran `korben
// build` did not write them and cannot fix them.


"#;

// korben-bdg
/// What the generated file may import, by runtime module. Only the names the
/// body actually mentions are written out.
const IMPORTS: &[(&str, &[&str])] = &[
    (
        "apply",
        &[
            "apply",
            "bad_binding",
            "bind_args",
            "call_member",
            "close_resource",
            "condition_matches",
            "field",
            "is_variant",
            "no_match",
            "propagate",
            "report",
            "variant_at",
            "vector_at",
            "vector_from",
            "vector_shape",
        ],
    ),
    ("ffi", &["CSignature", "CType"]),
    ("loc", &["Loc"]),
    ("task", &["await_value", "enter_scope", "exit_scope", "spawn"]),
    (
        "value",
        &[
            "display", "member", "Arg", "Body", "Caller", "Flow", "Function", "Outcome", "Param",
            "Value",
        ],
    ),
];

const TAIL: &str = r#"use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

/// Route an error to the innermost enclosing block that handles one.
macro_rules! kb_try {
    ($label:lifetime, $expr:expr) => {
        match $expr {
            Ok(value) => value,
            Err(err) => break $label Err(err),
        }
    };
}

/// A source location, written compactly because there are a great many.
#[inline(always)]
fn kl(file: u32, start: u32, end: u32) -> Loc {
    Loc::new(file, start, end)
}

/// Cache runtime function lookups so a hot call is not a string match.
// korben-d3j
// Each builtin the program references gets its own slot, initialised once per
// thread. Reaching one used to mean hashing its name and probing a map on
// every call -- for `get`, `len` and `=` that is inside every loop the program
// runs. The set of builtins is known when this file is written, so the lookup
// can be settled here instead of repeated at run time.
fn builtin_or_panic(name: &'static str) -> Value {
    korben_runtime::std::builtin(name)
        .unwrap_or_else(|| panic!("runtime is missing `{name}`"))
}

type Impls = HashMap<(String, String), HashMap<String, Value>>;

thread_local! {
    static IMPLS: RefCell<Impls> = RefCell::new(HashMap::new());
    static METHOD_OWNER: RefCell<HashMap<String, String>> = RefCell::new(HashMap::new());
}

fn register_impl(protocol: &str, type_name: &str, method: &str, value: Value) {
    METHOD_OWNER.with(|owner| {
        owner.borrow_mut().insert(method.to_string(), protocol.to_string());
    });
    IMPLS.with(|impls| {
        impls
            .borrow_mut()
            .entry((protocol.to_string(), type_name.to_string()))
            .or_default()
            .insert(method.to_string(), value);
    });
}

/// The host the runtime calls back into. Generated programs own no closure
/// bodies of their own, so only method lookup and output are interesting.
struct Host;

impl Caller for Host {
    fn call_host(&mut self, function: &Value, _args: Vec<Arg>, loc: Loc) -> Outcome {
        Err(Flow::fault(
            korben_runtime::Fault::new(
                "not-callable",
                format!("`{}` has no callable body", function.type_name()),
                loc,
            ),
        ))
    }

    fn find_method(&mut self, receiver: &Value, method: &str) -> Option<Value> {
        let type_name = receiver.type_name();
        let protocol = METHOD_OWNER.with(|owner| owner.borrow().get(method).cloned());
        if let Some(protocol) = protocol {
            let found = IMPLS.with(|impls| {
                impls
                    .borrow()
                    .get(&(protocol, type_name.clone()))
                    .and_then(|methods| methods.get(method).cloned())
            });
            if found.is_some() {
                return found;
            }
        }
        korben_runtime::std::method_of(&type_name, method)
    }

    fn write(&mut self, text: &str) {
        use std::io::Write;
        let mut stdout = std::io::stdout();
        let _ = stdout.write_all(text.as_bytes());
        let _ = stdout.flush();
    }
}
"#;

impl Generator {
    fn label(&mut self) -> String {
        let label = format!("'b{}", self.next_label);
        self.next_label += 1;
        label
    }

    fn temp(&mut self) -> String {
        let name = format!("__t{}", self.next_temp);
        self.next_temp += 1;
        name
    }

    fn error_label(&self) -> String {
        self.error_labels.last().cloned().unwrap_or_else(|| "'b0".to_string())
    }

    fn program(&mut self, program: &Program) {
        // korben-bdg
        // The imports depend on what the body turns out to reference, so the
        // header is prepended once the body exists.
        let header_at = self.out.len();

        for module in &program.modules {
            for def in &module.types {
                let _ = writeln!(self.out, "\n// type {}", def.name);
            }
            for foreign in &module.foreign {
                self.foreign(foreign);
            }
            for function in &module.functions {
                self.function(function);
            }
            for konst in &module.consts {
                self.constant(konst);
            }
        }

        // Protocol implementations are registered once at start-up.
        let _ = writeln!(self.out, "\nfn install_impls() {{");
        for module in &program.modules {
            for def in &module.impls {
                for (method, symbol) in &def.methods {
                    let _ = writeln!(
                        self.out,
                        "    register_impl({}, {}, {}, g_{symbol}());",
                        quote(&def.protocol),
                        quote(&def.type_name),
                        quote(method)
                    );
                }
            }
        }
        let _ = writeln!(self.out, "}}");

        let pending = std::mem::take(&mut self.pending);
        self.out.push_str(&pending);
        self.main(program);

        // korben-bdg
        let header = self.header();
        self.out.insert_str(header_at, &header);
    }

    // korben-bdg
    /// The file's header, with only the imports the body turned out to use.
    ///
    /// The runtime offers more than any one program needs, and importing all of
    /// it means importing what this program does not use -- which rustc reports,
    /// about a file nobody wrote.
    fn header(&self) -> String {
        let mut out = String::from(PRELUDE);
        // korben-d3j
        if !self.builtin_slots.is_empty() {
            let mut slots: Vec<(&String, &usize)> = self.builtin_slots.iter().collect();
            slots.sort_by_key(|(_, slot)| **slot);
            out.push_str("thread_local! {\n");
            for (name, slot) in slots {
                let _ = writeln!(
                    out,
                    "    static KB{slot}: Value = builtin_or_panic({});",
                    quote(name)
                );
            }
            out.push_str("}\n\n");
        }
        for (module, names) in IMPORTS {
            let used: Vec<&str> =
                names.iter().copied().filter(|name| self.mentions(name)).collect();
            match used.len() {
                0 => {}
                1 => {
                    let _ = writeln!(out, "use korben_runtime::{module}::{};", used[0]);
                }
                _ => {
                    let _ = writeln!(out, "use korben_runtime::{module}::{{{}}};", used.join(", "));
                }
            }
        }
        out.push_str(TAIL);
        out
    }

    // korben-bdg
    /// Whether the body refers to `name` as a word rather than as part of one.
    fn mentions(&self, name: &str) -> bool {
        self.out.match_indices(name).any(|(at, _)| {
            let before = self.out[..at].chars().next_back();
            let after = self.out[at + name.len()..].chars().next();
            let boundary =
                |ch: Option<char>| ch.map(|ch| !ch.is_alphanumeric() && ch != '_').unwrap_or(true);
            boundary(before) && boundary(after)
        })
    }

    fn main(&mut self, program: &Program) {
        let _ = writeln!(self.out, "\nfn main() {{");
        let _ = writeln!(self.out, "    korben_runtime::loc::install_sources(SOURCES);");
        let _ = writeln!(
            self.out,
            "    korben_runtime::std::set_program_args(std::env::args().skip(1).collect());"
        );
        let _ = writeln!(self.out, "    install_impls();");
        let _ = writeln!(self.out, "    let mut host = Host;");
        match &program.entry {
            Some(entry) => {
                let _ =
                    writeln!(self.out, "    match f_{entry}(&mut host, Vec::new(), Loc::NONE) {{");
                let _ = writeln!(self.out, "        Ok(value) => {{");
                // `main` returning `Err` is a failed process exit.
                let _ = writeln!(self.out, "            if is_variant(&value, \"Err\") {{");
                let _ = writeln!(
                    self.out,
                    "                let payload = variant_at(&value, 0).unwrap_or(Value::Nil);"
                );
                let _ = writeln!(
                    self.out,
                    "                eprintln!(\"error: {{}}\", display(&payload));"
                );
                let _ = writeln!(self.out, "                std::process::exit(1);");
                let _ = writeln!(self.out, "            }}");
                let _ = writeln!(self.out, "        }}");
                let _ = writeln!(self.out, "        Err(flow) => {{");
                let _ = writeln!(self.out, "            eprint!(\"{{}}\", report(flow));");
                let _ = writeln!(self.out, "            std::process::exit(1);");
                let _ = writeln!(self.out, "        }}");
                let _ = writeln!(self.out, "    }}");
            }
            None => {
                let _ =
                    writeln!(self.out, "    eprintln!(\"error: this program defines no `main`\");");
                let _ = writeln!(self.out, "    std::process::exit(1);");
            }
        }
        let _ = writeln!(self.out, "}}");
    }

    fn params_fn(&mut self, symbol: &str, params: &[ir::Param]) {
        let _ = writeln!(self.out, "fn p_{symbol}() -> Vec<Param> {{");
        let _ = writeln!(self.out, "    vec![");
        for param in params {
            let keyword = match &param.keyword {
                Some(keyword) => format!("Some(Rc::from({}))", quote(keyword)),
                None => "None".to_string(),
            };
            let _ = writeln!(
                self.out,
                "        Param {{ name: Rc::from({}), keyword: {keyword}, has_default: {} }},",
                quote(&param.name),
                param.default.is_some()
            );
        }
        let _ = writeln!(self.out, "    ]");
        let _ = writeln!(self.out, "}}");
    }

    /// A foreign function compiles to a wrapper that marshals into the C ABI
    /// through the same runtime the interpreter uses.
    fn foreign(&mut self, foreign: &ir::ForeignFn) {
        let symbol = &foreign.symbol;
        let params: Vec<String> = foreign
            .params
            .iter()
            .enumerate()
            .map(|(index, _)| {
                format!(
                    "Param {{ name: Rc::from(\"a{index}\"), keyword: None, has_default: false }}"
                )
            })
            .collect();
        let _ = writeln!(self.out, "fn p_{symbol}() -> Vec<Param> {{");
        let _ = writeln!(self.out, "    vec![{}]", params.join(", "));
        let _ = writeln!(self.out, "}}");

        let c_params: Vec<String> =
            foreign.params.iter().map(|ty| format!("CType::{ty:?}")).collect();
        let _ = writeln!(self.out, "fn s_{symbol}() -> CSignature {{");
        let _ = writeln!(self.out, "    CSignature {{");
        let _ = writeln!(self.out, "        library: {}.to_string(),", quote(&foreign.library));
        let _ = writeln!(self.out, "        symbol: {}.to_string(),", quote(&foreign.c_symbol));
        let _ = writeln!(self.out, "        params: vec![{}],", c_params.join(", "));
        let _ = writeln!(self.out, "        ret: CType::{:?},", foreign.ret);
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(self.out, "}}");

        let _ = writeln!(self.out, "fn g_{symbol}() -> Value {{");
        let _ = writeln!(self.out, "    thread_local! {{");
        let _ = writeln!(
            self.out,
            "        static V: Value = Value::Fn(Rc::new(Function {{ name: {}.to_string(), params: p_{symbol}(), body: Body::Rust(Box::new(f_{symbol})), is_async: false }}));",
            quote(&foreign.name)
        );
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(self.out, "    V.with(|value| value.clone())");
        let _ = writeln!(self.out, "}}");

        let _ = writeln!(
            self.out,
            "fn f_{symbol}(__c: &mut dyn Caller, __args: Vec<Arg>, __loc: Loc) -> Outcome {{"
        );
        let _ = writeln!(self.out, "    thread_local! {{");
        let _ = writeln!(self.out, "        static SIG: CSignature = s_{symbol}();");
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(
            self.out,
            "    let values: Vec<Value> = __args.into_iter().map(|arg| arg.value).collect();"
        );
        let _ = writeln!(
            self.out,
            "    SIG.with(|sig| korben_runtime::ffi::call(sig, values, {}, __loc))",
            quote(&foreign.name)
        );
        let _ = writeln!(self.out, "}}");
    }

    fn function(&mut self, function: &ir::Function) {
        let symbol = &function.symbol;
        self.params_fn(symbol, &function.params);

        // The function as a value, for references and higher-order use.
        let _ = writeln!(self.out, "fn g_{symbol}() -> Value {{");
        let _ = writeln!(self.out, "    thread_local! {{");
        let _ = writeln!(
            self.out,
            "        static V: Value = Value::Fn(Rc::new(Function {{ name: {}.to_string(), params: p_{symbol}(), body: Body::Rust(Box::new(f_{symbol})), is_async: {} }}));",
            quote(&function.name),
            function.is_async
        );
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(self.out, "    V.with(|value| value.clone())");
        let _ = writeln!(self.out, "}}");

        let _ = writeln!(
            self.out,
            "fn f_{symbol}(__c: &mut dyn Caller, __args: Vec<Arg>, __loc: Loc) -> Outcome {{"
        );
        let _ = writeln!(self.out, "    let mut __args = __args;");
        let _ = writeln!(self.out, "    loop {{");
        let _ = writeln!(
            self.out,
            "        let __bound = bind_args({}, &p_{symbol}(), {}, __args, __loc)?;",
            quote(&function.name),
            loc_expr(loc_of(function.span))
        );
        let _ = writeln!(self.out, "        let mut __supplied = __bound.into_iter();");
        for param in &function.params {
            let default = match &param.default {
                Some(default) => {
                    // A default is ordinary code and may fail, so it is given a
                    // label to break out to.
                    let label = self.label();
                    self.error_labels.push(label.clone());
                    let expr = self.expr(default);
                    self.error_labels.pop();
                    // korben-ajx
                    // Most defaults cannot fail -- `{}`, `""`, a number -- and
                    // nothing breaks to the label. Wrapping those in a labelled
                    // block anyway makes rustc warn about an unused label and a
                    // redundant paren, in a file nobody wrote. The label is kept
                    // only when the default actually reaches for it.
                    if expr.contains(&format!("break {label} ")) {
                        format!(
                            "match ({label}: {{ Ok({expr}) }}) {{ Ok(v) => v, Err(e) => return Err(e) }}"
                        )
                    } else {
                        expr
                    }
                }
                None => "Value::Nil".to_string(),
            };
            let _ = writeln!(
                self.out,
                "        let {} = match __supplied.next().flatten() {{ Some(v) => v, None => {default} }};",
                param.slot
            );
        }

        let body_label = self.label();
        self.error_labels.push(body_label.clone());
        self.recur_labels.push(body_label.clone());
        let body = self.block(&function.body, &body_label);
        self.recur_labels.pop();
        self.error_labels.pop();

        let _ = writeln!(self.out, "        let __out: Outcome = {body};");
        let _ = writeln!(self.out, "        match __out {{");
        let _ = writeln!(
            self.out,
            "            Err(Flow::Recur(values)) => {{ __args = values.into_iter().map(Arg::positional).collect(); continue; }}"
        );
        // `?` propagation stops at the function boundary.
        let _ = writeln!(self.out, "            Err(Flow::Propagate(value)) => break Ok(value),");
        let _ = writeln!(self.out, "            other => break other,");
        let _ = writeln!(self.out, "        }}");
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(self.out, "}}");
    }

    fn constant(&mut self, konst: &ir::Const) {
        let label = self.label();
        self.error_labels.push(label.clone());
        let value = self.expr(&konst.value);
        self.error_labels.pop();
        let symbol = &konst.symbol;
        let _ = writeln!(self.out, "fn gc_{symbol}() -> Outcome {{");
        let _ = writeln!(self.out, "    thread_local! {{");
        let _ =
            writeln!(self.out, "        static V: RefCell<Option<Value>> = RefCell::new(None);");
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(
            self.out,
            "    if let Some(value) = V.with(|slot| slot.borrow().clone()) {{ return Ok(value); }}"
        );
        let _ = writeln!(self.out, "    let __c: &mut dyn Caller = &mut Host;");
        // korben-str
        // The label exists for `?` to break to. A constant whose value never
        // propagates never breaks, and an unused label is a warning about code
        // nobody wrote.
        if value.contains(&label) {
            let _ = writeln!(self.out, "    let __out: Outcome = {label}: {{ Ok({value}) }};");
        } else {
            let _ = writeln!(self.out, "    let __out: Outcome = Ok({value});");
        }
        let _ = writeln!(self.out, "    let value = __out?;");
        let _ = writeln!(self.out, "    V.with(|slot| *slot.borrow_mut() = Some(value.clone()));");
        let _ = writeln!(self.out, "    Ok(value)");
        let _ = writeln!(self.out, "}}");
    }

    /// A block compiles to a labeled block whose value is an `Outcome`.
    fn block(&mut self, block: &ir::Block, label: &str) -> String {
        let mut out = format!("{label}: {{\n");
        out.push_str(&self.stmts(&block.stmts, label));
        out.push('}');
        out
    }

    /// Statements, with `defer` wrapping everything that follows it.
    ///
    /// A block's value is its last statement's value; a binding yields nil,
    /// which is what the interpreter does too.
    fn stmts(&mut self, stmts: &[Stmt], label: &str) -> String {
        let mut out = String::new();
        for (index, stmt) in stmts.iter().enumerate() {
            let is_last = index + 1 == stmts.len();
            match stmt {
                Stmt::Defer { body, .. } => {
                    // Everything after the `defer` runs first, then the deferred
                    // body, on every exit path. Nesting gives last-in-first-out.
                    let rest_label = self.label();
                    self.error_labels.push(rest_label.clone());
                    let rest = self.stmts(&stmts[index + 1..], &rest_label);
                    self.error_labels.pop();

                    let defer_label = self.label();
                    self.error_labels.push(defer_label.clone());
                    let deferred = self.stmts(&body.stmts, &defer_label);
                    self.error_labels.pop();

                    let _ = writeln!(out, "let __rest: Outcome = {rest_label}: {{\n{rest}}};");
                    let _ =
                        writeln!(out, "let __deferred: Outcome = {defer_label}: {{\n{deferred}}};");
                    let _ = writeln!(out, "match __rest {{");
                    let _ = writeln!(
                        out,
                        "    Ok(value) => {{ kb_try!({label}, __deferred); Ok(value) }}"
                    );
                    let _ = writeln!(out, "    Err(err) => {{ let _ = __deferred; Err(err) }}");
                    let _ = writeln!(out, "}}");
                    return out;
                }
                Stmt::Let { pattern, value, span } => {
                    let value_expr = self.expr(value);
                    let subject = self.temp();
                    let _ = writeln!(out, "let {subject} = {value_expr};");
                    match pattern {
                        Pattern::Bind(slot, _) => {
                            let _ = writeln!(out, "let {slot} = {subject};");
                        }
                        Pattern::Wildcard(_) => {}
                        _ => {
                            // A refutable binding fails loudly rather than silently.
                            let arm = self.label();
                            let mut tests = String::new();
                            self.emit_pattern(pattern, &subject, &arm, &mut tests);
                            let _ = writeln!(out, "let __ok = {arm}: {{");
                            out.push_str(&tests);
                            let _ = writeln!(out, "    true");
                            let _ = writeln!(out, "}};");
                            let _ = writeln!(
                                out,
                                "if !__ok {{ break {label} Err(bad_binding(&{subject}, {})); }}",
                                loc_expr(loc_of(*span))
                            );
                        }
                    }
                    if is_last {
                        let _ = writeln!(out, "Ok(Value::Nil)");
                    }
                }
                Stmt::Var { slot, value, .. } => {
                    let value_expr = self.expr(value);
                    let _ = writeln!(out, "let mut {slot} = {value_expr};");
                    if is_last {
                        let _ = writeln!(out, "Ok(Value::Nil)");
                    }
                }
                Stmt::Expr(expr) => {
                    self.leaves = false;
                    let value_expr = self.expr(expr);
                    // korben-str
                    // An expression that always leaves -- a `recur`, or a match
                    // whose every arm leaves -- has no value to wrap.
                    let leaves = self.leaves || value_expr.trim_start().starts_with("break ");
                    self.leaves = false;
                    if is_last && !leaves {
                        let _ = writeln!(out, "Ok({value_expr})");
                    } else if is_last {
                        let _ = writeln!(out, "{value_expr}");
                    } else {
                        let _ = writeln!(out, "let _ = {value_expr};");
                    }
                }
            }
        }
        if stmts.is_empty() {
            let _ = writeln!(out, "Ok(Value::Nil)");
        }
        out
    }

    // ------------------------------------------------------------- patterns

    /// Emit the test-and-bind sequence for a pattern, breaking to `fail` when
    /// it does not match. Bindings are introduced with `let`.
    fn emit_pattern(&mut self, pattern: &Pattern, subject: &str, fail: &str, out: &mut String) {
        match pattern {
            Pattern::Wildcard(_) => {}
            Pattern::Bind(slot, _) => {
                let _ = writeln!(out, "    let {slot} = {subject}.clone();");
            }
            Pattern::Nil(_) => {
                let _ = writeln!(
                    out,
                    "    if !matches!({subject}, Value::Nil) {{ break {fail} false; }}"
                );
            }
            Pattern::Bool(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::Bool({value})) {{ break {fail} false; }}"
                );
            }
            Pattern::Int(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::Int({value})) {{ break {fail} false; }}"
                );
            }
            Pattern::Float(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::Float({}f64)) {{ break {fail} false; }}",
                    float_literal(*value)
                );
            }
            Pattern::Str(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::str({})) {{ break {fail} false; }}",
                    quote(value)
                );
            }
            Pattern::Keyword(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::keyword({})) {{ break {fail} false; }}",
                    quote(value)
                );
            }
            Pattern::Variant { name, positional, named, .. } => {
                let _ = writeln!(
                    out,
                    "    if !is_variant(&{subject}, {}) {{ break {fail} false; }}",
                    quote(name)
                );
                for (index, sub) in positional.iter().enumerate() {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match variant_at(&{subject}, {index}) {{ Some(v) => v, None => break {fail} false }};"
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
                for (field_name, sub) in named {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match member(&{subject}, {}) {{ Some(v) => v, None => break {fail} false }};",
                        quote(field_name)
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
            }
            Pattern::Vector { items, rest, .. } => {
                let _ = writeln!(
                    out,
                    "    if !vector_shape(&{subject}, {}, {}) {{ break {fail} false; }}",
                    items.len(),
                    rest.is_some()
                );
                for (index, sub) in items.iter().enumerate() {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match vector_at(&{subject}, {index}) {{ Some(v) => v, None => break {fail} false }};"
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
                if let Some(Some(slot)) = rest {
                    let _ =
                        writeln!(out, "    let {slot} = vector_from(&{subject}, {});", items.len());
                }
            }
            Pattern::Members { entries, .. } => {
                for (key, sub) in entries {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match member(&{subject}, {}) {{ Some(v) => v, None => break {fail} false }};",
                        quote(key)
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
            }
        }
    }

    // ---------------------------------------------------------- expressions

    fn expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Nil(_) => "Value::Nil".to_string(),
            Expr::Bool(value, _) => format!("Value::Bool({value})"),
            Expr::Int(value, _) => format!("Value::Int({value}i64)"),
            Expr::Float(value, _) => format!("Value::Float({}f64)", float_literal(*value)),
            Expr::Str(value, _) => format!("Value::str({})", quote(value)),
            Expr::Keyword(name, _) => format!("Value::keyword({})", quote(name)),
            Expr::Symbol(name, _) => format!("Value::symbol({})", quote(name)),
            Expr::Ref(reference, span) => self.reference(reference, *span),
            Expr::Vector(items, _) => {
                let parts: Vec<String> = items.iter().map(|item| self.expr(item)).collect();
                format!("Value::vector(vec![{}])", parts.join(", "))
            }
            Expr::Set(items, _) => {
                let parts: Vec<String> = items.iter().map(|item| self.expr(item)).collect();
                format!("Value::set(vec![{}])", parts.join(", "))
            }
            Expr::Map(entries, _) => {
                let parts: Vec<String> = entries
                    .iter()
                    .map(|(key, value)| format!("({}, {})", self.expr(key), self.expr(value)))
                    .collect();
                format!("Value::map(vec![{}])", parts.join(", "))
            }
            Expr::Record { type_name, fields, .. } => {
                let parts: Vec<String> = fields
                    .iter()
                    .map(|(name, value)| format!("({}, {})", quote(name), self.expr(value)))
                    .collect();
                let name = match type_name {
                    Some(name) => format!("Some({})", quote(name)),
                    None => "None".to_string(),
                };
                format!("Value::record({name}, vec![{}])", parts.join(", "))
            }
            Expr::Concat(parts, _) => {
                let pieces: Vec<String> = parts
                    .iter()
                    .map(|part| format!("text.push_str(&display(&{}));", self.expr(part)))
                    .collect();
                format!("{{ let mut text = String::new(); {} Value::str(text) }}", pieces.join(" "))
            }
            Expr::If { cond, then, els, .. } => {
                let cond = self.expr(cond);
                let then = self.expr(then);
                let els = match els {
                    Some(els) => self.expr(els),
                    None => "Value::Nil".to_string(),
                };
                format!("if ({cond}).is_truthy() {{ {then} }} else {{ {els} }}")
            }
            // Short-circuiting: each operand is evaluated only if it is reached.
            Expr::And(operands, _) | Expr::Or(operands, _) => {
                let stop_on = matches!(expr, Expr::And(..));
                let identity = if stop_on { "true" } else { "false" };
                let mut out = format!("{{ let mut __v = Value::Bool({identity});\n");
                let mut closers = 0usize;
                for operand in operands {
                    let value = self.expr(operand);
                    let _ = writeln!(out, "__v = {value};");
                    let test = if stop_on { "__v.is_truthy()" } else { "!__v.is_truthy()" };
                    let _ = writeln!(out, "if {test} {{");
                    closers += 1;
                }
                for _ in 0..closers {
                    out.push_str("}\n");
                }
                out.push_str("__v }");
                out
            }
            Expr::Do(block, _) => {
                let label = self.label();
                self.error_labels.push(label.clone());
                let body = self.block(block, &label);
                self.error_labels.pop();
                let outer = self.error_label();
                format!("kb_try!({outer}, {body})")
            }
            Expr::Lambda(lambda, span) => self.lambda(lambda, *span),
            Expr::Call { callee, args, span } => self.call(callee, args, *span),
            Expr::Field { target, name, span } => {
                let target = self.expr(target);
                let outer = self.error_label();
                format!(
                    "kb_try!({outer}, field(&{target}, {}, {}))",
                    quote(name),
                    loc_expr(loc_of(*span))
                )
            }
            Expr::Match { scrutinee, arms, span } => self.match_expr(scrutinee, arms, *span),
            Expr::Loop { bindings, body, span } => self.loop_expr(bindings, body, *span),
            Expr::Recur(args, span) => {
                let parts: Vec<String> = args.iter().map(|arg| self.expr(arg)).collect();
                let target =
                    self.recur_labels.last().cloned().unwrap_or_else(|| self.error_label());
                let _ = span;
                format!("break {target} Err(Flow::Recur(vec![{}]))", parts.join(", "))
            }
            Expr::Assign { slot, value, .. } => {
                let value = self.expr(value);
                format!("{{ {slot} = {value}; Value::Nil }}")
            }
            Expr::Propagate(inner, span) => {
                let inner = self.expr(inner);
                let outer = self.error_label();
                format!("kb_try!({outer}, propagate({inner}, {}))", loc_expr(loc_of(*span)))
            }
            Expr::Throw(inner, span) => {
                let inner = self.expr(inner);
                let outer = self.error_label();
                format!("break {outer} Err(Flow::Condition({inner}, {}))", loc_expr(loc_of(*span)))
            }
            Expr::Try { body, catches, finally, .. } => {
                self.try_expr(body, catches, finally.as_deref())
            }
            Expr::With { slot, value, body, span } => {
                let value = self.expr(value);
                let label = self.label();
                self.error_labels.push(label.clone());
                let body = self.block(body, &label);
                self.error_labels.pop();
                let outer = self.error_label();
                format!(
                    "{{ let __res = {value}; let {slot} = __res.clone(); let __out: Outcome = {body}; close_resource(__c, &__res, {}); kb_try!({outer}, __out) }}",
                    loc_expr(loc_of(*span))
                )
            }
            Expr::Unsafe(block, _) => {
                let label = self.label();
                self.error_labels.push(label.clone());
                let body = self.block(block, &label);
                self.error_labels.pop();
                let outer = self.error_label();
                format!("kb_try!({outer}, {body})")
            }
            // A scope joins its children on the way out, or cancels them when
            // the body is already failing.
            Expr::TaskScope { slot, body, span } => {
                let label = self.label();
                self.error_labels.push(label.clone());
                let compiled = self.block(body, &label);
                self.error_labels.pop();
                let outer = self.error_label();
                let _ = span;
                format!(
                    "{{ let __scope = enter_scope({}); let {slot} = __scope.clone(); \
                     let __out: Outcome = {compiled}; \
                     let __closed = exit_scope(__c, &__scope, __out.is_err()); \
                     let __value = kb_try!({outer}, __out); \
                     kb_try!({outer}, __closed.map(|_| Value::Nil)); __value }}",
                    quote(slot)
                )
            }
            Expr::Spawn { scope, thunk, span } => {
                let scope = self.expr(scope);
                let scope_slot = self.temp();
                let thunk = self.expr(thunk);
                let thunk_slot = self.temp();
                let outer = self.error_label();
                format!(
                    "{{ let {scope_slot} = {scope}; let {thunk_slot} = {thunk}; \
                     kb_try!({outer}, spawn(&{scope_slot}, {thunk_slot}, {})) }}",
                    loc_expr(loc_of(*span))
                )
            }
            Expr::Await(inner, span) => {
                let inner = self.expr(inner);
                let slot = self.temp();
                let outer = self.error_label();
                format!(
                    "{{ let {slot} = {inner}; kb_try!({outer}, await_value(__c, &{slot}, {})) }}",
                    loc_expr(loc_of(*span))
                )
            }
            Expr::Quote(value, _) => quote_value(value),
        }
    }

    fn reference(&mut self, reference: &Ref, span: korben_syntax::Span) -> String {
        match reference {
            Ref::Local(slot) => format!("{slot}.clone()"),
            // korben-d3j
            Ref::Builtin(name) => match self.builtin_slots.get(name) {
                Some(slot) => format!("KB{slot}.with(Value::clone)"),
                // Every builtin a program references is collected during
                // lowering, so this is unreachable; falling back keeps a
                // future caller that skips that step compiling.
                None => format!("builtin_or_panic({})", quote(name)),
            },
            Ref::Ctor { type_name, variant, fields } => {
                let variant = match variant {
                    Some(variant) => format!("Some({})", quote(variant)),
                    None => "None".to_string(),
                };
                let names: Vec<String> = fields.iter().map(|field| quote(field)).collect();
                format!("Value::ctor({}, {variant}, &[{}])", quote(type_name), names.join(", "))
            }
            Ref::Method { protocol, name } => {
                format!("Value::method({}, {})", quote(protocol), quote(name))
            }
            Ref::Unit { type_name, variant } => {
                format!("Value::variant({}, {}, Vec::new())", quote(type_name), quote(variant))
            }
            Ref::Global(symbol) => match self.symbols.get(symbol) {
                Some(Symbol::Const) => {
                    let outer = self.error_label();
                    let _ = span;
                    format!("kb_try!({outer}, gc_{symbol}())")
                }
                _ => format!("g_{symbol}()"),
            },
        }
    }

    fn lambda(&mut self, lambda: &ir::Lambda, span: korben_syntax::Span) -> String {
        // A closure captures the values it needs by cloning, which is cheap
        // because every value is reference counted.
        let index = self.next_lambda;
        self.next_lambda += 1;
        let params_fn = format!("pl_{index}");

        let mut params = String::new();
        let _ = writeln!(self.pending, "fn {params_fn}() -> Vec<Param> {{");
        let _ = writeln!(self.pending, "    vec![");
        for param in &lambda.params {
            let keyword = match &param.keyword {
                Some(keyword) => format!("Some(Rc::from({}))", quote(keyword)),
                None => "None".to_string(),
            };
            let _ = writeln!(
                self.pending,
                "        Param {{ name: Rc::from({}), keyword: {keyword}, has_default: {} }},",
                quote(&param.name),
                param.default.is_some()
            );
        }
        let _ = writeln!(self.pending, "    ]");
        let _ = writeln!(self.pending, "}}");
        let _ = &mut params;

        let body_label = self.label();
        self.error_labels.push(body_label.clone());
        self.recur_labels.push(body_label.clone());
        let body = self.block(&lambda.body, &body_label);
        self.recur_labels.pop();
        self.error_labels.pop();

        // A closure is a value that outlives the block it was written in, so it
        // copies what it reads rather than borrowing or moving it. Values are
        // reference counted, so copying is cheap.
        let mut out = String::from("{\n");
        for (index, slot) in lambda.captures.iter().enumerate() {
            // korben-bdg: a slot already starts with `_`, so no separator is needed.
            let _ = writeln!(out, "let _cap{index}{slot} = {slot}.clone();");
        }
        let _ = writeln!(
            out,
            "Value::Fn(Rc::new(Function {{ name: {}.to_string(), is_async: false, params: {params_fn}(), body: Body::Rust(Box::new(move |__c: &mut dyn Caller, __args: Vec<Arg>, __loc: Loc| -> Outcome {{",
            quote(&lambda.name)
        );
        for (index, slot) in lambda.captures.iter().enumerate() {
            let _ = writeln!(out, "    let {slot} = _cap{index}{slot}.clone();");
        }
        let _ = writeln!(out, "    let mut __args = __args;");
        let _ = writeln!(out, "    loop {{");
        let _ = writeln!(
            out,
            "        let __bound = bind_args({}, &{params_fn}(), {}, __args, __loc)?;",
            quote(&lambda.name),
            loc_expr(loc_of(span))
        );
        let _ = writeln!(out, "        let mut __supplied = __bound.into_iter();");
        for param in &lambda.params {
            let _ = writeln!(
                out,
                "        let {} = __supplied.next().flatten().unwrap_or(Value::Nil);",
                param.slot
            );
        }
        let _ = writeln!(out, "        let __out: Outcome = {body};");
        let _ = writeln!(out, "        match __out {{");
        let _ = writeln!(
            out,
            "            Err(Flow::Recur(values)) => {{ __args = values.into_iter().map(Arg::positional).collect(); continue; }}"
        );
        let _ = writeln!(out, "            Err(Flow::Propagate(value)) => break Ok(value),");
        let _ = writeln!(out, "            other => break other,");
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "    }}");
        // Close: closure body, Box::new, Body::Rust, Function, Rc::new, Value::Fn.
        let _ = writeln!(out, "}})) }}))");
        out.push('}');
        out
    }

    // korben-b13
    /// Integer arithmetic on operands the checker settled as `Int`.
    ///
    /// The general path builds a `vec![Arg::positional(..)]`, looks the builtin
    /// up and goes through `apply`, which is a lot of work to add two numbers
    /// the compiler already knows are numbers.
    ///
    /// Anything the fast path does not cover falls through to that general path
    /// rather than being reimplemented here: a value that turns out not to be
    /// an `Int` after all, and an overflow. Overflow is rare and its fault
    /// message is exact, so delegating it keeps the two paths identical by
    /// construction instead of by my copying the wording. And the checker is
    /// not sound everywhere -- `type_of` is partial by design -- so the
    /// fallback is what makes reading it here safe at all.
    fn int_arithmetic(
        &mut self,
        callee: &Expr,
        args: &[ir::Arg],
        span: korben_syntax::Span,
    ) -> Option<String> {
        let Expr::Ref(Ref::Builtin(name), _) = callee else { return None };
        let operator = match name.as_str() {
            "std.core/+" => "checked_add",
            "std.core/-" => "checked_sub",
            "std.core/*" => "checked_mul",
            _ => return None,
        };
        // Two operands only. The variadic fold is the general path's business.
        let [left, right] = args else { return None };
        if left.keyword.is_some() || right.keyword.is_some() {
            return None;
        }
        if !self.is_int(&left.value) || !self.is_int(&right.value) {
            return None;
        }

        let loc = loc_expr(loc_of(span));
        let left_code = self.expr(&left.value);
        let right_code = self.expr(&right.value);
        let l = self.temp();
        let r = self.temp();
        let outer = self.error_label();
        let general = match self.builtin_slots.get(name.as_str()) {
            Some(slot) => format!("KB{slot}.with(Value::clone)"),
            None => format!("builtin_or_panic({})", quote(name)),
        };
        Some(format!(
            "{{ let {l} = {left_code}; let {r} = {right_code}; \
             match (&{l}, &{r}) {{ \
             (Value::Int(a), Value::Int(b)) => match a.{operator}(*b) {{ \
             Some(v) => Value::Int(v), \
             None => kb_try!({outer}, apply(__c, &{general}, \
             vec![Arg::positional({l}.clone()), Arg::positional({r}.clone())], {loc})) }}, \
             _ => kb_try!({outer}, apply(__c, &{general}, \
             vec![Arg::positional({l}.clone()), Arg::positional({r}.clone())], {loc})) }} }}"
        ))
    }

    // korben-b13
    /// Whether the checker settled this expression as `Int`.
    fn is_int(&self, expr: &Expr) -> bool {
        matches!(
            self.types.get(&expr.span()),
            Some(crate::types::Type::Con(name, params)) if &**name == "Int" && params.is_empty()
        )
    }

    fn call(&mut self, callee: &Expr, args: &[ir::Arg], span: korben_syntax::Span) -> String {
        // The callee and every argument are evaluated into temporaries first.
        // They may each need the caller, and a borrow of it cannot still be
        // open when `apply` takes its own.
        let loc = loc_expr(loc_of(span));
        let mut out = String::from("{ ");

        // `(receiver.name args)` is a member call, which the runtime resolves
        // the same way for both execution modes.
        if let Expr::Field { target, name, .. } = callee {
            let receiver = self.expr(target);
            let slot = self.temp();
            let _ = write!(out, "let {slot} = {receiver}; ");
            let mut parts = Vec::with_capacity(args.len());
            for arg in args {
                let value = self.expr(&arg.value);
                let arg_slot = self.temp();
                let _ = write!(out, "let {arg_slot} = {value}; ");
                parts.push(match &arg.keyword {
                    Some(keyword) => format!("Arg::named({}, {arg_slot})", quote(keyword)),
                    None => format!("Arg::positional({arg_slot})"),
                });
            }
            let outer = self.error_label();
            let _ = write!(
                out,
                "kb_try!({outer}, call_member(__c, &{slot}, {}, vec![{}], {loc})) }}",
                quote(name),
                parts.join(", ")
            );
            return out;
        }

        // korben-b13
        if let Some(specialised) = self.int_arithmetic(callee, args, span) {
            return specialised;
        }

        // A direct call to a known function skips building a value for it.
        let direct = match callee {
            Expr::Ref(Ref::Global(symbol), _)
                if self.symbols.get(symbol) == Some(&Symbol::Function) =>
            {
                Some(symbol.clone())
            }
            _ => None,
        };
        let callee_slot = match &direct {
            Some(_) => None,
            None => {
                let expr = self.expr(callee);
                let slot = self.temp();
                let _ = write!(out, "let {slot} = {expr}; ");
                Some(slot)
            }
        };

        let mut parts = Vec::with_capacity(args.len());
        for arg in args {
            let value = self.expr(&arg.value);
            let slot = self.temp();
            let _ = write!(out, "let {slot} = {value}; ");
            parts.push(match &arg.keyword {
                Some(keyword) => format!("Arg::named({}, {slot})", quote(keyword)),
                None => format!("Arg::positional({slot})"),
            });
        }
        let arguments = format!("vec![{}]", parts.join(", "));
        let outer = self.error_label();
        match direct {
            Some(symbol) => {
                let _ = write!(out, "kb_try!({outer}, f_{symbol}(__c, {arguments}, {loc}))");
            }
            None => {
                let slot = callee_slot.unwrap();
                let _ = write!(out, "kb_try!({outer}, apply(__c, &{slot}, {arguments}, {loc}))");
            }
        }
        out.push_str(" }");
        out
    }

    fn match_expr(
        &mut self,
        scrutinee: &Expr,
        arms: &[ir::MatchArm],
        span: korben_syntax::Span,
    ) -> String {
        let scrutinee = self.expr(scrutinee);
        let dispatch = self.label();
        let mut out = format!("{{ let __s = {scrutinee};\n{dispatch}: {{\n");
        // korben-str
        // An arm that cannot fail ends the match: nothing after it can run, it
        // needs no label to fail to, and the no-match fallback below becomes
        // unreachable. Emitting all three anyway is what made generated code
        // warn about itself.
        let mut always_matches = false;
        for arm in arms {
            let arm_label = self.label();
            let mut tests = String::new();
            self.emit_pattern(&arm.pattern, "__s", &arm_label, &mut tests);
            let guard = match &arm.guard {
                Some(guard) => {
                    let guard = self.expr(guard);
                    format!("    if !({guard}).is_truthy() {{ break {arm_label} false; }}\n")
                }
                None => String::new(),
            };
            let body = self.expr(&arm.body);
            // Parenthesised because `break 'label { .. }` reads as an
            // unlabelled break carrying a labelled value, which rustc warns
            // about.
            // korben-str
            // A body that is itself a `break` -- a `recur`, or a propagation --
            // already leaves; breaking to this match with it would be an
            // expression after one that never returns.
            // korben-str
            // Only a block needs the parentheses -- `break 'label { .. }` is
            // what reads as an unlabelled break carrying a labelled value.
            // Wrapping everything else is its own warning.
            let leave = if body.trim_start().starts_with("break ") {
                format!("        {body};")
            } else if body.trim_start().starts_with('{') {
                format!("        break {dispatch} ({body});")
            } else {
                format!("        break {dispatch} {body};")
            };
            if tests.is_empty() && guard.is_empty() {
                let _ = writeln!(out, "    {}", leave.trim_start());
                always_matches = true;
                break;
            }
            let _ = writeln!(out, "    let _ = {arm_label}: {{");
            out.push_str(&tests);
            out.push_str(&guard);
            let _ = writeln!(out, "{leave}");
            let _ = writeln!(out, "    }};");
        }
        if !always_matches {
            let outer = self.error_label();
            let _ =
                writeln!(out, "    break {outer} Err(no_match(&__s, {}));", loc_expr(loc_of(span)));
        }
        let _ = writeln!(out, "}} }}");
        // korben-str
        // With every arm leaving by itself -- a match of `recur`s, say --
        // nothing breaks to this match at all: the label is unused and the
        // match never yields a value to whoever asked for one.
        if !out.contains(&format!("break {dispatch} ")) {
            out = out.replace(&format!("{dispatch}: {{\n"), "{\n");
            self.leaves = true;
        }
        out
    }

    fn loop_expr(
        &mut self,
        bindings: &[(String, Expr)],
        body: &ir::Block,
        span: korben_syntax::Span,
    ) -> String {
        let mut out = String::from("{\n");
        for (index, (_, value)) in bindings.iter().enumerate() {
            let value = self.expr(value);
            let _ = writeln!(out, "let mut __loop{index} = {value};");
        }
        let label = self.label();
        self.error_labels.push(label.clone());
        self.recur_labels.push(label.clone());
        let compiled = self.block(body, &label);
        self.recur_labels.pop();
        self.error_labels.pop();

        let _ = writeln!(out, "loop {{");
        for (index, (slot, _)) in bindings.iter().enumerate() {
            let _ = writeln!(out, "    let {slot} = __loop{index}.clone();");
        }
        let _ = writeln!(out, "    let __out: Outcome = {compiled};");
        let _ = writeln!(out, "    match __out {{");
        let _ = writeln!(out, "        Err(Flow::Recur(values)) => {{");
        let _ = writeln!(out, "            if values.len() != {} {{", bindings.len());
        let outer = self.error_label();
        let _ = writeln!(
            out,
            "                break {outer} Err(korben_runtime::Flow::fault(korben_runtime::Fault::new(\"recur-arity\", format!(\"`recur` passed {{}} value(s) but the loop binds {}\", values.len()), {})));",
            bindings.len(),
            loc_expr(loc_of(span))
        );
        let _ = writeln!(out, "            }}");
        let _ = writeln!(out, "            let mut values = values;");
        for index in (0..bindings.len()).rev() {
            let _ = writeln!(out, "            __loop{index} = values.remove({index});");
        }
        let _ = writeln!(out, "            continue;");
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "        other => break kb_try!({outer}, other),");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        out.push('}');
        out
    }

    fn try_expr(
        &mut self,
        body: &ir::Block,
        catches: &[ir::CatchArm],
        finally: Option<&ir::Block>,
    ) -> String {
        let body_label = self.label();
        self.error_labels.push(body_label.clone());
        let compiled = self.block(body, &body_label);
        self.error_labels.pop();

        let mut out = format!("{{ let __out: Outcome = {compiled};\n");
        if !catches.is_empty() {
            let handled = self.label();
            let _ = writeln!(out, "let __out: Outcome = match __out {{");
            let _ = writeln!(out, "    Err(Flow::Condition(__value, __cl)) => {handled}: {{");
            for arm in catches {
                let arm_label = self.label();
                self.error_labels.push(arm_label.clone());
                let arm_body = self.block(&arm.body, &arm_label);
                self.error_labels.pop();
                let _ = writeln!(
                    out,
                    "        if condition_matches({}, &__value) {{",
                    quote(&arm.condition)
                );
                let _ = writeln!(out, "            let {} = __value.clone();", arm.slot);
                // korben-str
                let _ = writeln!(out, "            break {handled} ({arm_body});");
                let _ = writeln!(out, "        }}");
            }
            let _ = writeln!(out, "        Err(Flow::Condition(__value, __cl))");
            let _ = writeln!(out, "    }},");
            let _ = writeln!(out, "    other => other,");
            let _ = writeln!(out, "}};");
        }
        if let Some(finally) = finally {
            let finally_label = self.label();
            self.error_labels.push(finally_label.clone());
            let compiled = self.block(finally, &finally_label);
            self.error_labels.pop();
            // Cleanup errors never mask the primary failure.
            let _ = writeln!(out, "let __cleanup: Outcome = {compiled};");
            let _ = writeln!(out, "if __out.is_ok() {{ let _ = __cleanup?; }}");
        }
        let outer = self.error_label();
        let _ = writeln!(out, "kb_try!({outer}, __out) }}");
        out
    }
}

// ------------------------------------------------------------------ helpers

fn loc_of(span: korben_syntax::Span) -> Loc {
    if span.is_synthetic() {
        Loc::NONE
    } else {
        Loc::new(span.file, span.start, span.end)
    }
}

fn loc_expr(loc: Loc) -> String {
    if loc.is_none() {
        "Loc::NONE".to_string()
    } else {
        format!("kl({}, {}, {})", loc.file, loc.start, loc.end)
    }
}

/// A Rust string literal for arbitrary text.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            ch => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn float_literal(value: f64) -> String {
    if value.is_nan() {
        return "f64::NAN".to_string();
    }
    if value.is_infinite() {
        return if value > 0.0 { "f64::INFINITY" } else { "f64::NEG_INFINITY" }.to_string();
    }
    let text = format!("{value:?}");
    text
}

/// Compile quoted data into the expression that rebuilds it.
fn quote_value(value: &korben_runtime::Value) -> String {
    use korben_runtime::Value;
    match value {
        Value::Nil => "Value::Nil".to_string(),
        Value::Bool(value) => format!("Value::Bool({value})"),
        Value::Int(value) => format!("Value::Int({value}i64)"),
        Value::Float(value) => format!("Value::Float({}f64)", float_literal(*value)),
        Value::Str(text) => format!("Value::str({})", quote(text)),
        Value::Keyword(name) => format!("Value::keyword({})", quote(name)),
        Value::Symbol(name) => format!("Value::symbol({})", quote(name)),
        Value::Vector(items) => {
            let parts: Vec<String> = items.iter().map(quote_value).collect();
            format!("Value::vector(vec![{}])", parts.join(", "))
        }
        Value::Set(items) => {
            let parts: Vec<String> = items.iter().map(quote_value).collect();
            format!("Value::set(vec![{}])", parts.join(", "))
        }
        Value::Map(map) => {
            let parts: Vec<String> = map
                .entries
                .iter()
                .map(|(key, value)| format!("({}, {})", quote_value(key), quote_value(value)))
                .collect();
            format!("Value::map(vec![{}])", parts.join(", "))
        }
        other => format!("Value::str({})", quote(&other.to_string())),
    }
}

// ---------------------------------------------------------- project emission

/// The runtime crate's source, embedded so that generated projects build
/// offline and reproducibly without a registry.
pub const RUNTIME_FILES: &[(&str, &str)] = &[
    ("src/lib.rs", include_str!("../../korben-runtime/src/lib.rs")),
    ("src/loc.rs", include_str!("../../korben-runtime/src/loc.rs")),
    ("src/value.rs", include_str!("../../korben-runtime/src/value.rs")),
    ("src/apply.rs", include_str!("../../korben-runtime/src/apply.rs")),
    ("src/ffi.rs", include_str!("../../korben-runtime/src/ffi.rs")),
    ("src/net.rs", include_str!("../../korben-runtime/src/net.rs")),
    ("src/profile.rs", include_str!("../../korben-runtime/src/profile.rs")),
    // korben-5k7
    ("src/signal.rs", include_str!("../../korben-runtime/src/signal.rs")),
    ("src/task.rs", include_str!("../../korben-runtime/src/task.rs")),
    ("src/std.rs", include_str!("../../korben-runtime/src/std.rs")),
    ("src/json.rs", include_str!("../../korben-runtime/src/json.rs")),
];

const RUNTIME_MANIFEST: &str = r#"[package]
name = "korben-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
"#;

/// Write a self-contained cargo project for `generated`.
pub fn write_project(
    dir: &std::path::Path,
    name: &str,
    version: &str,
    release: bool,
    generated: &Generated,
) -> std::io::Result<()> {
    let runtime = dir.join("runtime");
    std::fs::create_dir_all(runtime.join("src"))?;
    std::fs::write(runtime.join("Cargo.toml"), RUNTIME_MANIFEST)?;
    for (path, contents) in RUNTIME_FILES {
        std::fs::write(runtime.join(path), contents)?;
    }

    std::fs::create_dir_all(dir.join("src"))?;
    let profile = if release {
        "\n[profile.release]\nopt-level = 3\nlto = true\ncodegen-units = 1\nstrip = true\npanic = \"abort\"\n"
    } else {
        ""
    };
    let manifest = format!(
        "# Generated by the Korben compiler. Do not edit.\n\
         [package]\nname = {}\nversion = {}\nedition = \"2021\"\n\n\
         [[bin]]\nname = {}\npath = \"src/main.rs\"\n\n\
         [dependencies]\nkorben-runtime = {{ path = \"runtime\" }}\n\n\
         # Standalone, so a surrounding cargo workspace does not absorb it.\n[workspace]\n{profile}",
        quote(name),
        quote(version),
        quote(name)
    );
    std::fs::write(dir.join("Cargo.toml"), manifest)?;

    let mut main = generated.main.clone();
    let mut table = String::from("\nstatic SOURCES: &[(&str, &str)] = &[\n");
    for (file, text) in &generated.sources {
        let _ = writeln!(table, "    ({}, {}),", quote(file), quote(text));
    }
    table.push_str("];\n");
    main.push_str(&table);
    std::fs::write(dir.join("src/main.rs"), main)?;
    Ok(())
}
