//! The native backend: core IR to Rust source.
//!
//! Per specification 18.3, the first native backend lowers typed Korben IR to
//! generated Rust and hands it to an isolated Rust compilation pipeline. The
//! generated source is internal but reproducible, and `korben build --emit rust`
//! prints it.
//!
//! Generated code links against `korben-runtime`, the same crate the
//! interpreter uses, so both execution modes share their standard library and
//! their notion of what a value is.

// korben-vtx

use crate::ir::{self, Expr, Pattern, Program, Ref, Stmt};
use korben_runtime::Loc;
use korben_syntax::diag::Diagnostic;
use korben_syntax::SourceMap;
use std::collections::HashMap;
use std::fmt::Write as _;

/// What a mangled global symbol refers to.
#[derive(Clone, Copy, PartialEq)]
enum Symbol {
    Function,
    Const,
}

pub struct Generated {
    pub main: String,
    /// File name and text of every source file, indexed by file id.
    pub sources: Vec<(String, String)>,
}

/// Emit the Rust source for a program.
pub fn generate(program: &Program, sources: &SourceMap) -> Result<Generated, Vec<Diagnostic>> {
    // Every builtin the program references must exist in the runtime.
    let mut missing = Vec::new();
    for name in &program.builtins {
        if korben_runtime::std::builtin(name).is_none() {
            missing.push(name.clone());
        }
    }
    if !missing.is_empty() {
        return Err(missing
            .into_iter()
            .map(|name| {
                Diagnostic::error(format!("`{name}` has no native implementation"))
                    .with_code("missing-runtime")
                    .note("the interpreter provides it, but the native backend does not yet")
                    .help("run this program with `korben run` until the backend catches up")
            })
            .collect());
    }

    let mut symbols = HashMap::new();
    for module in &program.modules {
        for function in &module.functions {
            symbols.insert(function.symbol.clone(), Symbol::Function);
        }
        for konst in &module.consts {
            symbols.insert(konst.symbol.clone(), Symbol::Const);
        }
    }

    let mut generator = Generator {
        out: String::new(),
        symbols,
        next_label: 0,
        next_temp: 0,
        next_lambda: 0,
        pending: String::new(),
        error_labels: Vec::new(),
        recur_labels: Vec::new(),
    };
    generator.program(program);

    let mut files = Vec::new();
    let mut index = 0u32;
    while let Some(file) = sources.get(index) {
        files.push((file.name.clone(), file.text.clone()));
        index += 1;
    }
    Ok(Generated { main: generator.out, sources: files })
}

struct Generator {
    out: String,
    symbols: HashMap<String, Symbol>,
    next_label: usize,
    next_temp: usize,
    next_lambda: usize,
    /// Top-level items produced while compiling an expression.
    pending: String,
    /// Innermost-last stack of labels that capture an error.
    error_labels: Vec<String>,
    /// Innermost-last stack of labels a `recur` targets.
    recur_labels: Vec<String>,
}

const PRELUDE: &str = r#"// Generated by the Korben compiler. Do not edit.
#![allow(unused_variables, unused_mut, unused_parens, unused_braces)]
#![allow(non_snake_case, non_upper_case_globals, dead_code, unused_imports, clippy::all)]

use korben_runtime::apply::{
    apply, bad_binding, bind_args, call_member, close_resource, condition_matches, field,
    is_variant, no_match, propagate, report, variant_at, vector_at, vector_from, vector_shape,
};
use korben_runtime::loc::Loc;
use korben_runtime::value::{
    display, member, Arg, Body, Caller, Flow, Function, Outcome, Param, Value,
};
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

/// Route an error to the innermost enclosing block that handles one.
macro_rules! kb_try {
    ($label:lifetime, $expr:expr) => {
        match $expr {
            Ok(value) => value,
            Err(err) => break $label Err(err),
        }
    };
}

/// A source location, written compactly because there are a great many.
#[inline(always)]
fn kl(file: u32, start: u32, end: u32) -> Loc {
    Loc::new(file, start, end)
}

/// Cache runtime function lookups so a hot call is not a string match.
fn kb(name: &'static str) -> Value {
    thread_local! {
        static CACHE: RefCell<HashMap<&'static str, Value>> = RefCell::new(HashMap::new());
    }
    CACHE.with(|cache| {
        if let Some(value) = cache.borrow().get(name) {
            return value.clone();
        }
        let value = korben_runtime::std::builtin(name)
            .unwrap_or_else(|| panic!("runtime is missing `{name}`"));
        cache.borrow_mut().insert(name, value.clone());
        value
    })
}

type Impls = HashMap<(String, String), HashMap<String, Value>>;

thread_local! {
    static IMPLS: RefCell<Impls> = RefCell::new(HashMap::new());
    static METHOD_OWNER: RefCell<HashMap<String, String>> = RefCell::new(HashMap::new());
}

fn register_impl(protocol: &str, type_name: &str, method: &str, value: Value) {
    METHOD_OWNER.with(|owner| {
        owner.borrow_mut().insert(method.to_string(), protocol.to_string());
    });
    IMPLS.with(|impls| {
        impls
            .borrow_mut()
            .entry((protocol.to_string(), type_name.to_string()))
            .or_default()
            .insert(method.to_string(), value);
    });
}

/// The host the runtime calls back into. Generated programs own no closure
/// bodies of their own, so only method lookup and output are interesting.
struct Host;

impl Caller for Host {
    fn call_host(&mut self, function: &Value, _args: Vec<Arg>, loc: Loc) -> Outcome {
        Err(Flow::fault(
            korben_runtime::Fault::new(
                "not-callable",
                format!("`{}` has no callable body", function.type_name()),
                loc,
            ),
        ))
    }

    fn find_method(&mut self, receiver: &Value, method: &str) -> Option<Value> {
        let type_name = receiver.type_name();
        let protocol = METHOD_OWNER.with(|owner| owner.borrow().get(method).cloned());
        if let Some(protocol) = protocol {
            let found = IMPLS.with(|impls| {
                impls
                    .borrow()
                    .get(&(protocol, type_name.clone()))
                    .and_then(|methods| methods.get(method).cloned())
            });
            if found.is_some() {
                return found;
            }
        }
        korben_runtime::std::method_of(&type_name, method)
    }

    fn write(&mut self, text: &str) {
        use std::io::Write;
        let mut stdout = std::io::stdout();
        let _ = stdout.write_all(text.as_bytes());
        let _ = stdout.flush();
    }
}
"#;

impl Generator {
    fn label(&mut self) -> String {
        let label = format!("'b{}", self.next_label);
        self.next_label += 1;
        label
    }

    fn temp(&mut self) -> String {
        let name = format!("__t{}", self.next_temp);
        self.next_temp += 1;
        name
    }

    fn error_label(&self) -> String {
        self.error_labels.last().cloned().unwrap_or_else(|| "'b0".to_string())
    }

    fn program(&mut self, program: &Program) {
        self.out.push_str(PRELUDE);

        for module in &program.modules {
            for def in &module.types {
                let _ = writeln!(self.out, "\n// type {}", def.name);
            }
            for function in &module.functions {
                self.function(function);
            }
            for konst in &module.consts {
                self.constant(konst);
            }
        }

        // Protocol implementations are registered once at start-up.
        let _ = writeln!(self.out, "\nfn install_impls() {{");
        for module in &program.modules {
            for def in &module.impls {
                for (method, symbol) in &def.methods {
                    let _ = writeln!(
                        self.out,
                        "    register_impl({}, {}, {}, g_{symbol}());",
                        quote(&def.protocol),
                        quote(&def.type_name),
                        quote(method)
                    );
                }
            }
        }
        let _ = writeln!(self.out, "}}");

        let pending = std::mem::take(&mut self.pending);
        self.out.push_str(&pending);
        self.main(program);
    }

    fn main(&mut self, program: &Program) {
        let _ = writeln!(self.out, "\nfn main() {{");
        let _ = writeln!(self.out, "    korben_runtime::loc::install_sources(SOURCES);");
        let _ = writeln!(
            self.out,
            "    korben_runtime::std::set_program_args(std::env::args().skip(1).collect());"
        );
        let _ = writeln!(self.out, "    install_impls();");
        let _ = writeln!(self.out, "    let mut host = Host;");
        match &program.entry {
            Some(entry) => {
                let _ =
                    writeln!(self.out, "    match f_{entry}(&mut host, Vec::new(), Loc::NONE) {{");
                let _ = writeln!(self.out, "        Ok(value) => {{");
                // `main` returning `Err` is a failed process exit.
                let _ = writeln!(self.out, "            if is_variant(&value, \"Err\") {{");
                let _ = writeln!(
                    self.out,
                    "                let payload = variant_at(&value, 0).unwrap_or(Value::Nil);"
                );
                let _ = writeln!(
                    self.out,
                    "                eprintln!(\"error: {{}}\", display(&payload));"
                );
                let _ = writeln!(self.out, "                std::process::exit(1);");
                let _ = writeln!(self.out, "            }}");
                let _ = writeln!(self.out, "        }}");
                let _ = writeln!(self.out, "        Err(flow) => {{");
                let _ = writeln!(self.out, "            eprint!(\"{{}}\", report(flow));");
                let _ = writeln!(self.out, "            std::process::exit(1);");
                let _ = writeln!(self.out, "        }}");
                let _ = writeln!(self.out, "    }}");
            }
            None => {
                let _ =
                    writeln!(self.out, "    eprintln!(\"error: this program defines no `main`\");");
                let _ = writeln!(self.out, "    std::process::exit(1);");
            }
        }
        let _ = writeln!(self.out, "}}");
    }

    fn params_fn(&mut self, symbol: &str, params: &[ir::Param]) {
        let _ = writeln!(self.out, "fn p_{symbol}() -> Vec<Param> {{");
        let _ = writeln!(self.out, "    vec![");
        for param in params {
            let keyword = match &param.keyword {
                Some(keyword) => format!("Some(Rc::from({}))", quote(keyword)),
                None => "None".to_string(),
            };
            let _ = writeln!(
                self.out,
                "        Param {{ name: Rc::from({}), keyword: {keyword}, has_default: {} }},",
                quote(&param.name),
                param.default.is_some()
            );
        }
        let _ = writeln!(self.out, "    ]");
        let _ = writeln!(self.out, "}}");
    }

    fn function(&mut self, function: &ir::Function) {
        let symbol = &function.symbol;
        self.params_fn(symbol, &function.params);

        // The function as a value, for references and higher-order use.
        let _ = writeln!(self.out, "fn g_{symbol}() -> Value {{");
        let _ = writeln!(self.out, "    thread_local! {{");
        let _ = writeln!(
            self.out,
            "        static V: Value = Value::Fn(Rc::new(Function {{ name: {}.to_string(), params: p_{symbol}(), body: Body::Rust(Box::new(f_{symbol})) }}));",
            quote(&function.name)
        );
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(self.out, "    V.with(|value| value.clone())");
        let _ = writeln!(self.out, "}}");

        let _ = writeln!(
            self.out,
            "fn f_{symbol}(__c: &mut dyn Caller, __args: Vec<Arg>, __loc: Loc) -> Outcome {{"
        );
        let _ = writeln!(self.out, "    let mut __args = __args;");
        let _ = writeln!(self.out, "    loop {{");
        let _ = writeln!(
            self.out,
            "        let __bound = bind_args({}, &p_{symbol}(), {}, __args, __loc)?;",
            quote(&function.name),
            loc_expr(loc_of(function.span))
        );
        let _ = writeln!(self.out, "        let mut __supplied = __bound.into_iter();");
        for param in &function.params {
            let default = match &param.default {
                Some(default) => {
                    // A default is ordinary code and may fail.
                    let label = self.label();
                    self.error_labels.push(label.clone());
                    let expr = self.expr(default);
                    self.error_labels.pop();
                    format!("match ({label}: {{ Ok({expr}) }}) {{ Ok(v) => v, Err(e) => return Err(e) }}")
                }
                None => "Value::Nil".to_string(),
            };
            let _ = writeln!(
                self.out,
                "        let {} = match __supplied.next().flatten() {{ Some(v) => v, None => {default} }};",
                param.slot
            );
        }

        let body_label = self.label();
        self.error_labels.push(body_label.clone());
        self.recur_labels.push(body_label.clone());
        let body = self.block(&function.body, &body_label);
        self.recur_labels.pop();
        self.error_labels.pop();

        let _ = writeln!(self.out, "        let __out: Outcome = {body};");
        let _ = writeln!(self.out, "        match __out {{");
        let _ = writeln!(
            self.out,
            "            Err(Flow::Recur(values)) => {{ __args = values.into_iter().map(Arg::positional).collect(); continue; }}"
        );
        // `?` propagation stops at the function boundary.
        let _ = writeln!(self.out, "            Err(Flow::Propagate(value)) => break Ok(value),");
        let _ = writeln!(self.out, "            other => break other,");
        let _ = writeln!(self.out, "        }}");
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(self.out, "}}");
    }

    fn constant(&mut self, konst: &ir::Const) {
        let label = self.label();
        self.error_labels.push(label.clone());
        let value = self.expr(&konst.value);
        self.error_labels.pop();
        let symbol = &konst.symbol;
        let _ = writeln!(self.out, "fn gc_{symbol}() -> Outcome {{");
        let _ = writeln!(self.out, "    thread_local! {{");
        let _ =
            writeln!(self.out, "        static V: RefCell<Option<Value>> = RefCell::new(None);");
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(
            self.out,
            "    if let Some(value) = V.with(|slot| slot.borrow().clone()) {{ return Ok(value); }}"
        );
        let _ = writeln!(self.out, "    let __c: &mut dyn Caller = &mut Host;");
        let _ = writeln!(self.out, "    let __out: Outcome = {label}: {{ Ok({value}) }};");
        let _ = writeln!(self.out, "    let value = __out?;");
        let _ = writeln!(self.out, "    V.with(|slot| *slot.borrow_mut() = Some(value.clone()));");
        let _ = writeln!(self.out, "    Ok(value)");
        let _ = writeln!(self.out, "}}");
    }

    /// A block compiles to a labeled block whose value is an `Outcome`.
    fn block(&mut self, block: &ir::Block, label: &str) -> String {
        let mut out = format!("{label}: {{\n");
        out.push_str(&self.stmts(&block.stmts, label));
        out.push('}');
        out
    }

    /// Statements, with `defer` wrapping everything that follows it.
    ///
    /// A block's value is its last statement's value; a binding yields nil,
    /// which is what the interpreter does too.
    fn stmts(&mut self, stmts: &[Stmt], label: &str) -> String {
        let mut out = String::new();
        for (index, stmt) in stmts.iter().enumerate() {
            let is_last = index + 1 == stmts.len();
            match stmt {
                Stmt::Defer { body, .. } => {
                    // Everything after the `defer` runs first, then the deferred
                    // body, on every exit path. Nesting gives last-in-first-out.
                    let rest_label = self.label();
                    self.error_labels.push(rest_label.clone());
                    let rest = self.stmts(&stmts[index + 1..], &rest_label);
                    self.error_labels.pop();

                    let defer_label = self.label();
                    self.error_labels.push(defer_label.clone());
                    let deferred = self.stmts(&body.stmts, &defer_label);
                    self.error_labels.pop();

                    let _ = writeln!(out, "let __rest: Outcome = {rest_label}: {{\n{rest}}};");
                    let _ =
                        writeln!(out, "let __deferred: Outcome = {defer_label}: {{\n{deferred}}};");
                    let _ = writeln!(out, "match __rest {{");
                    let _ = writeln!(
                        out,
                        "    Ok(value) => {{ kb_try!({label}, __deferred); Ok(value) }}"
                    );
                    let _ = writeln!(out, "    Err(err) => {{ let _ = __deferred; Err(err) }}");
                    let _ = writeln!(out, "}}");
                    return out;
                }
                Stmt::Let { pattern, value, span } => {
                    let value_expr = self.expr(value);
                    let subject = self.temp();
                    let _ = writeln!(out, "let {subject} = {value_expr};");
                    match pattern {
                        Pattern::Bind(slot, _) => {
                            let _ = writeln!(out, "let {slot} = {subject};");
                        }
                        Pattern::Wildcard(_) => {}
                        _ => {
                            // A refutable binding fails loudly rather than silently.
                            let arm = self.label();
                            let mut tests = String::new();
                            self.emit_pattern(pattern, &subject, &arm, &mut tests);
                            let _ = writeln!(out, "let __ok = {arm}: {{");
                            out.push_str(&tests);
                            let _ = writeln!(out, "    true");
                            let _ = writeln!(out, "}};");
                            let _ = writeln!(
                                out,
                                "if !__ok {{ break {label} Err(bad_binding(&{subject}, {})); }}",
                                loc_expr(loc_of(*span))
                            );
                        }
                    }
                    if is_last {
                        let _ = writeln!(out, "Ok(Value::Nil)");
                    }
                }
                Stmt::Var { slot, value, .. } => {
                    let value_expr = self.expr(value);
                    let _ = writeln!(out, "let mut {slot} = {value_expr};");
                    if is_last {
                        let _ = writeln!(out, "Ok(Value::Nil)");
                    }
                }
                Stmt::Expr(expr) => {
                    let value_expr = self.expr(expr);
                    if is_last {
                        let _ = writeln!(out, "Ok({value_expr})");
                    } else {
                        let _ = writeln!(out, "let _ = {value_expr};");
                    }
                }
            }
        }
        if stmts.is_empty() {
            let _ = writeln!(out, "Ok(Value::Nil)");
        }
        out
    }

    // ------------------------------------------------------------- patterns

    /// Emit the test-and-bind sequence for a pattern, breaking to `fail` when
    /// it does not match. Bindings are introduced with `let`.
    fn emit_pattern(&mut self, pattern: &Pattern, subject: &str, fail: &str, out: &mut String) {
        match pattern {
            Pattern::Wildcard(_) => {}
            Pattern::Bind(slot, _) => {
                let _ = writeln!(out, "    let {slot} = {subject}.clone();");
            }
            Pattern::Nil(_) => {
                let _ = writeln!(
                    out,
                    "    if !matches!({subject}, Value::Nil) {{ break {fail} false; }}"
                );
            }
            Pattern::Bool(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::Bool({value})) {{ break {fail} false; }}"
                );
            }
            Pattern::Int(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::Int({value})) {{ break {fail} false; }}"
                );
            }
            Pattern::Float(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::Float({}f64)) {{ break {fail} false; }}",
                    float_literal(*value)
                );
            }
            Pattern::Str(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::str({})) {{ break {fail} false; }}",
                    quote(value)
                );
            }
            Pattern::Keyword(value, _) => {
                let _ = writeln!(
                    out,
                    "    if !{subject}.eq_value(&Value::keyword({})) {{ break {fail} false; }}",
                    quote(value)
                );
            }
            Pattern::Variant { name, positional, named, .. } => {
                let _ = writeln!(
                    out,
                    "    if !is_variant(&{subject}, {}) {{ break {fail} false; }}",
                    quote(name)
                );
                for (index, sub) in positional.iter().enumerate() {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match variant_at(&{subject}, {index}) {{ Some(v) => v, None => break {fail} false }};"
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
                for (field_name, sub) in named {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match member(&{subject}, {}) {{ Some(v) => v, None => break {fail} false }};",
                        quote(field_name)
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
            }
            Pattern::Vector { items, rest, .. } => {
                let _ = writeln!(
                    out,
                    "    if !vector_shape(&{subject}, {}, {}) {{ break {fail} false; }}",
                    items.len(),
                    rest.is_some()
                );
                for (index, sub) in items.iter().enumerate() {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match vector_at(&{subject}, {index}) {{ Some(v) => v, None => break {fail} false }};"
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
                if let Some(Some(slot)) = rest {
                    let _ =
                        writeln!(out, "    let {slot} = vector_from(&{subject}, {});", items.len());
                }
            }
            Pattern::Members { entries, .. } => {
                for (key, sub) in entries {
                    let temp = self.temp();
                    let _ = writeln!(
                        out,
                        "    let {temp} = match member(&{subject}, {}) {{ Some(v) => v, None => break {fail} false }};",
                        quote(key)
                    );
                    self.emit_pattern(sub, &temp, fail, out);
                }
            }
        }
    }

    // ---------------------------------------------------------- expressions

    fn expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Nil(_) => "Value::Nil".to_string(),
            Expr::Bool(value, _) => format!("Value::Bool({value})"),
            Expr::Int(value, _) => format!("Value::Int({value}i64)"),
            Expr::Float(value, _) => format!("Value::Float({}f64)", float_literal(*value)),
            Expr::Str(value, _) => format!("Value::str({})", quote(value)),
            Expr::Keyword(name, _) => format!("Value::keyword({})", quote(name)),
            Expr::Symbol(name, _) => format!("Value::symbol({})", quote(name)),
            Expr::Ref(reference, span) => self.reference(reference, *span),
            Expr::Vector(items, _) => {
                let parts: Vec<String> = items.iter().map(|item| self.expr(item)).collect();
                format!("Value::vector(vec![{}])", parts.join(", "))
            }
            Expr::Set(items, _) => {
                let parts: Vec<String> = items.iter().map(|item| self.expr(item)).collect();
                format!("Value::set(vec![{}])", parts.join(", "))
            }
            Expr::Map(entries, _) => {
                let parts: Vec<String> = entries
                    .iter()
                    .map(|(key, value)| format!("({}, {})", self.expr(key), self.expr(value)))
                    .collect();
                format!("Value::map(vec![{}])", parts.join(", "))
            }
            Expr::Record { type_name, fields, .. } => {
                let parts: Vec<String> = fields
                    .iter()
                    .map(|(name, value)| format!("({}, {})", quote(name), self.expr(value)))
                    .collect();
                let name = match type_name {
                    Some(name) => format!("Some({})", quote(name)),
                    None => "None".to_string(),
                };
                format!("Value::record({name}, vec![{}])", parts.join(", "))
            }
            Expr::Concat(parts, _) => {
                let pieces: Vec<String> = parts
                    .iter()
                    .map(|part| format!("text.push_str(&display(&{}));", self.expr(part)))
                    .collect();
                format!("{{ let mut text = String::new(); {} Value::str(text) }}", pieces.join(" "))
            }
            Expr::If { cond, then, els, .. } => {
                let cond = self.expr(cond);
                let then = self.expr(then);
                let els = match els {
                    Some(els) => self.expr(els),
                    None => "Value::Nil".to_string(),
                };
                format!("if ({cond}).is_truthy() {{ {then} }} else {{ {els} }}")
            }
            // Short-circuiting: each operand is evaluated only if it is reached.
            Expr::And(operands, _) | Expr::Or(operands, _) => {
                let stop_on = matches!(expr, Expr::And(..));
                let identity = if stop_on { "true" } else { "false" };
                let mut out = format!("{{ let mut __v = Value::Bool({identity});\n");
                let mut closers = 0usize;
                for operand in operands {
                    let value = self.expr(operand);
                    let _ = writeln!(out, "__v = {value};");
                    let test = if stop_on { "__v.is_truthy()" } else { "!__v.is_truthy()" };
                    let _ = writeln!(out, "if {test} {{");
                    closers += 1;
                }
                for _ in 0..closers {
                    out.push_str("}\n");
                }
                out.push_str("__v }");
                out
            }
            Expr::Do(block, _) => {
                let label = self.label();
                self.error_labels.push(label.clone());
                let body = self.block(block, &label);
                self.error_labels.pop();
                let outer = self.error_label();
                format!("kb_try!({outer}, {body})")
            }
            Expr::Lambda(lambda, span) => self.lambda(lambda, *span),
            Expr::Call { callee, args, span } => self.call(callee, args, *span),
            Expr::Field { target, name, span } => {
                let target = self.expr(target);
                let outer = self.error_label();
                format!(
                    "kb_try!({outer}, field(&{target}, {}, {}))",
                    quote(name),
                    loc_expr(loc_of(*span))
                )
            }
            Expr::Match { scrutinee, arms, span } => self.match_expr(scrutinee, arms, *span),
            Expr::Loop { bindings, body, span } => self.loop_expr(bindings, body, *span),
            Expr::Recur(args, span) => {
                let parts: Vec<String> = args.iter().map(|arg| self.expr(arg)).collect();
                let target =
                    self.recur_labels.last().cloned().unwrap_or_else(|| self.error_label());
                let _ = span;
                format!("break {target} Err(Flow::Recur(vec![{}]))", parts.join(", "))
            }
            Expr::Assign { slot, value, .. } => {
                let value = self.expr(value);
                format!("{{ {slot} = {value}; Value::Nil }}")
            }
            Expr::Propagate(inner, span) => {
                let inner = self.expr(inner);
                let outer = self.error_label();
                format!("kb_try!({outer}, propagate({inner}, {}))", loc_expr(loc_of(*span)))
            }
            Expr::Throw(inner, span) => {
                let inner = self.expr(inner);
                let outer = self.error_label();
                format!("break {outer} Err(Flow::Condition({inner}, {}))", loc_expr(loc_of(*span)))
            }
            Expr::Try { body, catches, finally, .. } => {
                self.try_expr(body, catches, finally.as_deref())
            }
            Expr::With { slot, value, body, span } => {
                let value = self.expr(value);
                let label = self.label();
                self.error_labels.push(label.clone());
                let body = self.block(body, &label);
                self.error_labels.pop();
                let outer = self.error_label();
                format!(
                    "{{ let __res = {value}; let {slot} = __res.clone(); let __out: Outcome = {body}; close_resource(__c, &__res, {}); kb_try!({outer}, __out) }}",
                    loc_expr(loc_of(*span))
                )
            }
            Expr::Unsafe(block, _) => {
                let label = self.label();
                self.error_labels.push(label.clone());
                let body = self.block(block, &label);
                self.error_labels.pop();
                let outer = self.error_label();
                format!("kb_try!({outer}, {body})")
            }
            Expr::Quote(value, _) => quote_value(value),
        }
    }

    fn reference(&mut self, reference: &Ref, span: korben_syntax::Span) -> String {
        match reference {
            Ref::Local(slot) => format!("{slot}.clone()"),
            Ref::Builtin(name) => format!("kb({})", quote(name)),
            Ref::Ctor { type_name, variant, fields } => {
                let variant = match variant {
                    Some(variant) => format!("Some({})", quote(variant)),
                    None => "None".to_string(),
                };
                let names: Vec<String> = fields.iter().map(|field| quote(field)).collect();
                format!("Value::ctor({}, {variant}, &[{}])", quote(type_name), names.join(", "))
            }
            Ref::Method { protocol, name } => {
                format!("Value::method({}, {})", quote(protocol), quote(name))
            }
            Ref::Unit { type_name, variant } => {
                format!("Value::variant({}, {}, Vec::new())", quote(type_name), quote(variant))
            }
            Ref::Global(symbol) => match self.symbols.get(symbol) {
                Some(Symbol::Const) => {
                    let outer = self.error_label();
                    let _ = span;
                    format!("kb_try!({outer}, gc_{symbol}())")
                }
                _ => format!("g_{symbol}()"),
            },
        }
    }

    fn lambda(&mut self, lambda: &ir::Lambda, span: korben_syntax::Span) -> String {
        // A closure captures the values it needs by cloning, which is cheap
        // because every value is reference counted.
        let index = self.next_lambda;
        self.next_lambda += 1;
        let params_fn = format!("pl_{index}");

        let mut params = String::new();
        let _ = writeln!(self.pending, "fn {params_fn}() -> Vec<Param> {{");
        let _ = writeln!(self.pending, "    vec![");
        for param in &lambda.params {
            let keyword = match &param.keyword {
                Some(keyword) => format!("Some(Rc::from({}))", quote(keyword)),
                None => "None".to_string(),
            };
            let _ = writeln!(
                self.pending,
                "        Param {{ name: Rc::from({}), keyword: {keyword}, has_default: {} }},",
                quote(&param.name),
                param.default.is_some()
            );
        }
        let _ = writeln!(self.pending, "    ]");
        let _ = writeln!(self.pending, "}}");
        let _ = &mut params;

        let body_label = self.label();
        self.error_labels.push(body_label.clone());
        self.recur_labels.push(body_label.clone());
        let body = self.block(&lambda.body, &body_label);
        self.recur_labels.pop();
        self.error_labels.pop();

        let mut out = String::new();
        let _ = writeln!(
            out,
            "Value::Fn(Rc::new(Function {{ name: {}.to_string(), params: {params_fn}(), body: Body::Rust(Box::new(move |__c: &mut dyn Caller, __args: Vec<Arg>, __loc: Loc| -> Outcome {{",
            quote(&lambda.name)
        );
        let _ = writeln!(out, "    let mut __args = __args;");
        let _ = writeln!(out, "    loop {{");
        let _ = writeln!(
            out,
            "        let __bound = bind_args({}, &{params_fn}(), {}, __args, __loc)?;",
            quote(&lambda.name),
            loc_expr(loc_of(span))
        );
        let _ = writeln!(out, "        let mut __supplied = __bound.into_iter();");
        for param in &lambda.params {
            let _ = writeln!(
                out,
                "        let {} = __supplied.next().flatten().unwrap_or(Value::Nil);",
                param.slot
            );
        }
        let _ = writeln!(out, "        let __out: Outcome = {body};");
        let _ = writeln!(out, "        match __out {{");
        let _ = writeln!(
            out,
            "            Err(Flow::Recur(values)) => {{ __args = values.into_iter().map(Arg::positional).collect(); continue; }}"
        );
        let _ = writeln!(out, "            Err(Flow::Propagate(value)) => break Ok(value),");
        let _ = writeln!(out, "            other => break other,");
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "    }}");
        // Close: closure body, Box::new, Body::Rust, Function, Rc::new, Value::Fn.
        let _ = writeln!(out, "}})) }}))");
        out
    }

    fn call(&mut self, callee: &Expr, args: &[ir::Arg], span: korben_syntax::Span) -> String {
        // The callee and every argument are evaluated into temporaries first.
        // They may each need the caller, and a borrow of it cannot still be
        // open when `apply` takes its own.
        let loc = loc_expr(loc_of(span));
        let mut out = String::from("{ ");

        // `(receiver.name args)` is a member call, which the runtime resolves
        // the same way for both execution modes.
        if let Expr::Field { target, name, .. } = callee {
            let receiver = self.expr(target);
            let slot = self.temp();
            let _ = write!(out, "let {slot} = {receiver}; ");
            let mut parts = Vec::with_capacity(args.len());
            for arg in args {
                let value = self.expr(&arg.value);
                let arg_slot = self.temp();
                let _ = write!(out, "let {arg_slot} = {value}; ");
                parts.push(match &arg.keyword {
                    Some(keyword) => format!("Arg::named({}, {arg_slot})", quote(keyword)),
                    None => format!("Arg::positional({arg_slot})"),
                });
            }
            let outer = self.error_label();
            let _ = write!(
                out,
                "kb_try!({outer}, call_member(__c, &{slot}, {}, vec![{}], {loc})) }}",
                quote(name),
                parts.join(", ")
            );
            return out;
        }

        // A direct call to a known function skips building a value for it.
        let direct = match callee {
            Expr::Ref(Ref::Global(symbol), _)
                if self.symbols.get(symbol) == Some(&Symbol::Function) =>
            {
                Some(symbol.clone())
            }
            _ => None,
        };
        let callee_slot = match &direct {
            Some(_) => None,
            None => {
                let expr = self.expr(callee);
                let slot = self.temp();
                let _ = write!(out, "let {slot} = {expr}; ");
                Some(slot)
            }
        };

        let mut parts = Vec::with_capacity(args.len());
        for arg in args {
            let value = self.expr(&arg.value);
            let slot = self.temp();
            let _ = write!(out, "let {slot} = {value}; ");
            parts.push(match &arg.keyword {
                Some(keyword) => format!("Arg::named({}, {slot})", quote(keyword)),
                None => format!("Arg::positional({slot})"),
            });
        }
        let arguments = format!("vec![{}]", parts.join(", "));
        let outer = self.error_label();
        match direct {
            Some(symbol) => {
                let _ = write!(out, "kb_try!({outer}, f_{symbol}(__c, {arguments}, {loc}))");
            }
            None => {
                let slot = callee_slot.unwrap();
                let _ = write!(out, "kb_try!({outer}, apply(__c, &{slot}, {arguments}, {loc}))");
            }
        }
        out.push_str(" }");
        out
    }

    fn match_expr(
        &mut self,
        scrutinee: &Expr,
        arms: &[ir::MatchArm],
        span: korben_syntax::Span,
    ) -> String {
        let scrutinee = self.expr(scrutinee);
        let dispatch = self.label();
        let mut out = format!("{{ let __s = {scrutinee};\n{dispatch}: {{\n");
        for arm in arms {
            let arm_label = self.label();
            let mut tests = String::new();
            self.emit_pattern(&arm.pattern, "__s", &arm_label, &mut tests);
            let guard = match &arm.guard {
                Some(guard) => {
                    let guard = self.expr(guard);
                    format!("    if !({guard}).is_truthy() {{ break {arm_label} false; }}\n")
                }
                None => String::new(),
            };
            let body = self.expr(&arm.body);
            let _ = writeln!(out, "    let __matched = {arm_label}: {{");
            out.push_str(&tests);
            out.push_str(&guard);
            let _ = writeln!(out, "        break {dispatch} {body};");
            let _ = writeln!(out, "    }};");
        }
        let outer = self.error_label();
        let _ = writeln!(out, "    break {outer} Err(no_match(&__s, {}));", loc_expr(loc_of(span)));
        let _ = writeln!(out, "}} }}");
        out
    }

    fn loop_expr(
        &mut self,
        bindings: &[(String, Expr)],
        body: &ir::Block,
        span: korben_syntax::Span,
    ) -> String {
        let mut out = String::from("{\n");
        for (index, (_, value)) in bindings.iter().enumerate() {
            let value = self.expr(value);
            let _ = writeln!(out, "let mut __loop{index} = {value};");
        }
        let label = self.label();
        self.error_labels.push(label.clone());
        self.recur_labels.push(label.clone());
        let compiled = self.block(body, &label);
        self.recur_labels.pop();
        self.error_labels.pop();

        let _ = writeln!(out, "loop {{");
        for (index, (slot, _)) in bindings.iter().enumerate() {
            let _ = writeln!(out, "    let {slot} = __loop{index}.clone();");
        }
        let _ = writeln!(out, "    let __out: Outcome = {compiled};");
        let _ = writeln!(out, "    match __out {{");
        let _ = writeln!(out, "        Err(Flow::Recur(values)) => {{");
        let _ = writeln!(out, "            if values.len() != {} {{", bindings.len());
        let outer = self.error_label();
        let _ = writeln!(
            out,
            "                break {outer} Err(korben_runtime::Flow::fault(korben_runtime::Fault::new(\"recur-arity\", format!(\"`recur` passed {{}} value(s) but the loop binds {}\", values.len()), {})));",
            bindings.len(),
            loc_expr(loc_of(span))
        );
        let _ = writeln!(out, "            }}");
        let _ = writeln!(out, "            let mut values = values;");
        for index in (0..bindings.len()).rev() {
            let _ = writeln!(out, "            __loop{index} = values.remove({index});");
        }
        let _ = writeln!(out, "            continue;");
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "        other => break kb_try!({outer}, other),");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        out.push('}');
        out
    }

    fn try_expr(
        &mut self,
        body: &ir::Block,
        catches: &[ir::CatchArm],
        finally: Option<&ir::Block>,
    ) -> String {
        let body_label = self.label();
        self.error_labels.push(body_label.clone());
        let compiled = self.block(body, &body_label);
        self.error_labels.pop();

        let mut out = format!("{{ let __out: Outcome = {compiled};\n");
        if !catches.is_empty() {
            let handled = self.label();
            let _ = writeln!(out, "let __out: Outcome = match __out {{");
            let _ = writeln!(out, "    Err(Flow::Condition(__value, __cl)) => {handled}: {{");
            for arm in catches {
                let arm_label = self.label();
                self.error_labels.push(arm_label.clone());
                let arm_body = self.block(&arm.body, &arm_label);
                self.error_labels.pop();
                let _ = writeln!(
                    out,
                    "        if condition_matches({}, &__value) {{",
                    quote(&arm.condition)
                );
                let _ = writeln!(out, "            let {} = __value.clone();", arm.slot);
                let _ = writeln!(out, "            break {handled} {arm_body};");
                let _ = writeln!(out, "        }}");
            }
            let _ = writeln!(out, "        Err(Flow::Condition(__value, __cl))");
            let _ = writeln!(out, "    }},");
            let _ = writeln!(out, "    other => other,");
            let _ = writeln!(out, "}};");
        }
        if let Some(finally) = finally {
            let finally_label = self.label();
            self.error_labels.push(finally_label.clone());
            let compiled = self.block(finally, &finally_label);
            self.error_labels.pop();
            // Cleanup errors never mask the primary failure.
            let _ = writeln!(out, "let __cleanup: Outcome = {compiled};");
            let _ = writeln!(out, "if __out.is_ok() {{ let _ = __cleanup?; }}");
        }
        let outer = self.error_label();
        let _ = writeln!(out, "kb_try!({outer}, __out) }}");
        out
    }
}

// ------------------------------------------------------------------ helpers

fn loc_of(span: korben_syntax::Span) -> Loc {
    if span.is_synthetic() {
        Loc::NONE
    } else {
        Loc::new(span.file, span.start, span.end)
    }
}

fn loc_expr(loc: Loc) -> String {
    if loc.is_none() {
        "Loc::NONE".to_string()
    } else {
        format!("kl({}, {}, {})", loc.file, loc.start, loc.end)
    }
}

/// A Rust string literal for arbitrary text.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            ch => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn float_literal(value: f64) -> String {
    if value.is_nan() {
        return "f64::NAN".to_string();
    }
    if value.is_infinite() {
        return if value > 0.0 { "f64::INFINITY" } else { "f64::NEG_INFINITY" }.to_string();
    }
    let text = format!("{value:?}");
    text
}

/// Compile quoted data into the expression that rebuilds it.
fn quote_value(value: &korben_runtime::Value) -> String {
    use korben_runtime::Value;
    match value {
        Value::Nil => "Value::Nil".to_string(),
        Value::Bool(value) => format!("Value::Bool({value})"),
        Value::Int(value) => format!("Value::Int({value}i64)"),
        Value::Float(value) => format!("Value::Float({}f64)", float_literal(*value)),
        Value::Str(text) => format!("Value::str({})", quote(text)),
        Value::Keyword(name) => format!("Value::keyword({})", quote(name)),
        Value::Symbol(name) => format!("Value::symbol({})", quote(name)),
        Value::Vector(items) => {
            let parts: Vec<String> = items.iter().map(quote_value).collect();
            format!("Value::vector(vec![{}])", parts.join(", "))
        }
        Value::Set(items) => {
            let parts: Vec<String> = items.iter().map(quote_value).collect();
            format!("Value::set(vec![{}])", parts.join(", "))
        }
        Value::Map(map) => {
            let parts: Vec<String> = map
                .entries
                .iter()
                .map(|(key, value)| format!("({}, {})", quote_value(key), quote_value(value)))
                .collect();
            format!("Value::map(vec![{}])", parts.join(", "))
        }
        other => format!("Value::str({})", quote(&other.to_string())),
    }
}

// ---------------------------------------------------------- project emission

/// The runtime crate's source, embedded so that generated projects build
/// offline and reproducibly without a registry.
const RUNTIME_FILES: &[(&str, &str)] = &[
    ("src/lib.rs", include_str!("../../korben-runtime/src/lib.rs")),
    ("src/loc.rs", include_str!("../../korben-runtime/src/loc.rs")),
    ("src/value.rs", include_str!("../../korben-runtime/src/value.rs")),
    ("src/apply.rs", include_str!("../../korben-runtime/src/apply.rs")),
    ("src/std.rs", include_str!("../../korben-runtime/src/std.rs")),
    ("src/json.rs", include_str!("../../korben-runtime/src/json.rs")),
];

const RUNTIME_MANIFEST: &str = r#"[package]
name = "korben-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
"#;

/// Write a self-contained cargo project for `generated`.
pub fn write_project(
    dir: &std::path::Path,
    name: &str,
    version: &str,
    release: bool,
    generated: &Generated,
) -> std::io::Result<()> {
    let runtime = dir.join("runtime");
    std::fs::create_dir_all(runtime.join("src"))?;
    std::fs::write(runtime.join("Cargo.toml"), RUNTIME_MANIFEST)?;
    for (path, contents) in RUNTIME_FILES {
        std::fs::write(runtime.join(path), contents)?;
    }

    std::fs::create_dir_all(dir.join("src"))?;
    let profile = if release {
        "\n[profile.release]\nopt-level = 3\nlto = true\ncodegen-units = 1\nstrip = true\npanic = \"abort\"\n"
    } else {
        ""
    };
    let manifest = format!(
        "# Generated by the Korben compiler. Do not edit.\n\
         [package]\nname = {}\nversion = {}\nedition = \"2021\"\n\n\
         [[bin]]\nname = {}\npath = \"src/main.rs\"\n\n\
         [dependencies]\nkorben-runtime = {{ path = \"runtime\" }}\n\n\
         # Standalone, so a surrounding cargo workspace does not absorb it.\n[workspace]\n{profile}",
        quote(name),
        quote(version),
        quote(name)
    );
    std::fs::write(dir.join("Cargo.toml"), manifest)?;

    let mut main = generated.main.clone();
    let mut table = String::from("\nstatic SOURCES: &[(&str, &str)] = &[\n");
    for (file, text) in &generated.sources {
        let _ = writeln!(table, "    ({}, {}),", quote(file), quote(text));
    }
    table.push_str("];\n");
    main.push_str(&table);
    std::fs::write(dir.join("src/main.rs"), main)?;
    Ok(())
}
