[workspace]
resolver = "2"
members = [
    "crates/korben-syntax",
    "crates/korben-runtime",
    "crates/korben-core",
    "crates/korben-lsp",
    "crates/korben-cli",
    "crates/korben-export",
    "crates/korben-export-macro",
    "crates/korben-adapter",
]

[workspace.package]
version = "0.7.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/leslierussell/korben"

[workspace.dependencies]
korben-syntax = { path = "crates/korben-syntax" }
korben-runtime = { path = "crates/korben-runtime" }
korben-core = { path = "crates/korben-core" }
korben-lsp = { path = "crates/korben-lsp" }
korben-export = { path = "crates/korben-export" }
korben-export-macro = { path = "crates/korben-export-macro" }
korben-adapter = { path = "crates/korben-adapter" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
