//! Writing the Korben half: the binding module `korben ffi rust` emits.
//!
//! Two layers, the way `korben ffi c` renders a header. The `raw-` declarations
//! are the foreign contract, and every one of them is an unsafe function. The
//! wrappers over them are what other Korben code imports: each calls its shim,
//! asks the adapter's error channel what happened, and returns `Ok` or `Err`.
//!
//! Every wrapper is fallible even when the Rust function is not, because the
//! boundary can fail where the function cannot: the adapter may have panicked,
//! and a returned string may have been one C cannot carry.

// korben-rm1

use crate::{kebab, Abi, Extracted, Signature, LAST_ERROR_SYMBOL};
use std::fmt::Write as _;

/// The Korben name of the raw declaration for `signature`.
fn raw_name(signature: &Signature) -> String {
    format!("raw-{}", kebab(&signature.name))
}

/// Render a binding module for everything `extracted` exports.
pub fn render(module: &str, library: &str, origin: &str, extracted: &Extracted) -> String {
    let mut out = String::new();
    let _ = writeln!(out, ";;; Bindings for `{library}`, generated from `{origin}`.");
    let _ = writeln!(out, ";;;");
    let _ = writeln!(out, ";;; Generated by `korben ffi rust`. Edits are lost on regeneration.");
    let _ = writeln!(out, ";;; The `raw-` declarations are unsafe: each asserts a contract the");
    let _ = writeln!(out, ";;; compiler cannot check. The wrappers under them are the part other");
    let _ = writeln!(out, ";;; Korben code is meant to use.");
    let _ = writeln!(out, ";;;");
    let _ = writeln!(out, ";;; Every wrapper returns a `Result` even where the Rust function does");
    let _ = writeln!(out, ";;; not, because the boundary can fail where the function cannot: the");
    let _ = writeln!(out, ";;; adapter may have panicked, and a returned string may have been one");
    let _ = writeln!(out, ";;; C cannot carry.");
    let _ = writeln!(out);
    let _ = writeln!(out, "(module {module})");
    let _ = writeln!(out);
    let _ = writeln!(out, "(ffi/c-library \"{library}\")");
    let _ = writeln!(out);
    let _ = writeln!(out, "; The adapter reports failure here rather than in a return value, so a");
    let _ =
        writeln!(out, "; function that legitimately returns zero is not read as having failed.");
    let _ = writeln!(out, "(ffi/c-fn adapter-last-error \"{LAST_ERROR_SYMBOL}\" [] -> CStr)");

    for signature in &extracted.exported {
        let _ = writeln!(out);
        let params: Vec<String> = signature
            .params
            .iter()
            .map(|param| format!("{}: {}", kebab(&param.name), param.abi.c_type()))
            .collect();
        let _ = writeln!(
            out,
            "(ffi/c-fn {} \"{}\" [{}] -> {})",
            raw_name(signature),
            signature.symbol(),
            params.join(" "),
            signature.ret.c_type()
        );
        let _ = writeln!(out);
        out.push_str(&wrapper(signature));
    }

    if !extracted.skipped.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, ";; Not exported:");
        for skipped in &extracted.skipped {
            let _ = writeln!(out, ";;   {} — {}", skipped.text, skipped.reason);
        }
    }
    out
}

/// The safe wrapper over one raw declaration.
fn wrapper(signature: &Signature) -> String {
    let name = kebab(&signature.name);
    let params: Vec<String> = signature
        .params
        .iter()
        .map(|param| format!("{}: {}", kebab(&param.name), param.abi.korben_type()))
        .collect();
    let arguments: Vec<String> = signature.params.iter().map(|param| kebab(&param.name)).collect();
    let call = if arguments.is_empty() {
        format!("({})", raw_name(signature))
    } else {
        format!("({} {})", raw_name(signature), arguments.join(" "))
    };

    let mut out = String::new();
    let _ =
        writeln!(out, ";;; `{}` in the adapter, through `{}`.", signature.name, signature.symbol());
    let _ = writeln!(
        out,
        "(pub fn {name} [{}] -> Result {} String !ffi !unsafe",
        params.join(" "),
        signature.ret.korben_type()
    );

    match signature.ret {
        // Nothing comes back, so the error channel is the whole answer.
        Abi::Unit => {
            let _ = writeln!(out, "  (unsafe {call})");
            let _ = writeln!(out, "  (match (unsafe (adapter-last-error))");
            let _ = writeln!(out, "    (Some ffi-message) (Err ffi-message)");
            let _ = writeln!(out, "    (None) (Ok nil)))");
        }
        // A `CStr` return is nullable, and null is how the shim reports that it
        // had nothing to hand back.
        Abi::Str => {
            let _ = writeln!(out, "  (let ffi-value (unsafe {call}))");
            let _ = writeln!(out, "  (match (unsafe (adapter-last-error))");
            let _ = writeln!(out, "    (Some ffi-message) (Err ffi-message)");
            let _ = writeln!(out, "    (None) (match ffi-value");
            let _ = writeln!(out, "             (Some ffi-text) (Ok ffi-text)");
            let _ =
                writeln!(out, "             (None) (Err \"the adapter returned no string\"))))");
        }
        _ => {
            let _ = writeln!(out, "  (let ffi-value (unsafe {call}))");
            let _ = writeln!(out, "  (match (unsafe (adapter-last-error))");
            let _ = writeln!(out, "    (Some ffi-message) (Err ffi-message)");
            let _ = writeln!(out, "    (None) (Ok ffi-value)))");
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::extract;

    fn module_for(source: &str) -> String {
        render("slug", "slug", "src/lib.rs", &extract(source))
    }

    #[test]
    fn a_string_function_gets_a_raw_declaration_and_a_wrapper() {
        let rendered = module_for("#[korben_export]\npub fn slugify(input: &str) -> String { }");
        assert!(
            rendered
                .contains("(ffi/c-fn raw-slugify \"korben_export_slugify\" [input: CStr] -> CStr)"),
            "{rendered}"
        );
        assert!(
            rendered
                .contains("(pub fn slugify [input: String] -> Result String String !ffi !unsafe"),
            "{rendered}"
        );
        assert!(rendered.contains("(let ffi-value (unsafe (raw-slugify input)))"), "{rendered}");
        assert!(rendered.contains("(Some ffi-text) (Ok ffi-text)"), "{rendered}");
    }

    #[test]
    fn the_error_channel_is_declared_once() {
        let rendered = module_for(
            "#[korben_export]\npub fn one(a: i64) -> i64 { }\n\
             #[korben_export]\npub fn two(a: i64) -> i64 { }",
        );
        assert_eq!(rendered.matches("adapter-last-error \"korben_export_last_error\"").count(), 1);
        assert!(rendered.contains("raw-one"), "{rendered}");
        assert!(rendered.contains("raw-two"), "{rendered}");
    }

    #[test]
    fn an_underscored_rust_name_becomes_a_kebab_korben_name() {
        let rendered = module_for(
            "#[korben_export]\npub fn parse_port(raw_text: String) -> Result<i64, String> { }",
        );
        assert!(rendered.contains("raw-parse-port \"korben_export_parse_port\""), "{rendered}");
        assert!(
            rendered.contains("[raw-text: CLong]") || rendered.contains("[raw-text: CStr]"),
            "{rendered}"
        );
        assert!(rendered.contains("(pub fn parse-port [raw-text: String]"), "{rendered}");
    }

    #[test]
    fn a_function_returning_nothing_reads_only_the_error_channel() {
        let rendered = module_for("#[korben_export]\npub fn log(text: &str) { }");
        assert!(rendered.contains("-> Result Unit String !ffi !unsafe"), "{rendered}");
        assert!(rendered.contains("  (unsafe (raw-log text))"), "{rendered}");
        assert!(rendered.contains("(Ok nil)"), "{rendered}");
    }

    #[test]
    fn what_could_not_be_exported_is_listed_with_its_reason() {
        let rendered = module_for("#[korben_export]\npub fn tally(rows: Vec<i64>) -> i64 { }");
        assert!(rendered.contains(";; Not exported:"), "{rendered}");
        assert!(rendered.contains("Vec<i64>"), "{rendered}");
    }
}
